var players = [
    // Inazuma Eleven 1
    {
        "Name": "Mark Evans",
        "Nickname": "Mark",
        "Description": "No one burns with a fiercer passion for football than Raimon's fearless captain!",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/GK.png",
        "Sprite": "./images/players/ie1/raimon/Mark.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": special_moves[1],
        "SM2": special_moves[3],
        "SM3": special_moves[4],
        "SM4": special_moves[5],
        "Kick": 72,
        "Body": 72,
        "Control": 70,
        "Guard": 77,
        "Speed": 68,
        "Stamina": 69,
        "Guts": 79,
        "FP": 191,
        "TP": 184,
    },
    {
        "Name": "Jack Wallside",
        "Nickname": "Jack",
        "Description": "This large-bodied defender forms a defensive wall, all by himself.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/raimon/Jack.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": special_moves[6],
        "SM2": special_moves[7],
        "SM3": special_moves[8],
        "SM4": special_moves[9],
        "Kick": 62,
        "Body": 68,
        "Control": 62,
        "Guard": 66,
        "Speed": 49,
        "Stamina": 54,
        "Guts": 54,
        "FP": 206,
        "TP": 165,
    },
    {
        "Name": "Jim Wraith",
        "Nickname": "Jim",
        "Description": "The colour of his eyes is a mystery thanks to his fringe.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/raimon/Jim.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": special_moves[10],
        "SM2": special_moves[11],
        "SM3": special_moves[12],
        "SM4": special_moves[13],
        "Kick": 58,
        "Body": 53,
        "Control": 75,
        "Guard": 59,
        "Speed": 53,
        "Stamina": 62,
        "Guts": 60,
        "FP": 195,
        "TP": 140,
    },
    {
        "Name": "Nathan Swift",
        "Nickname": "Nathan",
        "Description": "A nimble defender. He has been friends with Endou for a long time.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/raimon/Nathan.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": special_moves[14],
        "SM2": special_moves[15],
        "SM3": special_moves[16],
        "SM4": special_moves[17],
        "Kick": 64,
        "Body": 58,
        "Control": 68,
        "Guard": 54,
        "Speed": 76,
        "Stamina": 58,
        "Guts": 56,
        "FP": 169,
        "TP": 156,
    },
    {
        "Name": "Tod Ironside",
        "Nickname": "Tod",
        "Description": "The team's mood-maker's great courage makes up for his small size.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/raimon/Tod.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": special_moves[18],
        "SM2": special_moves[19],
        "SM3": special_moves[20],
        "SM4": special_moves[21],
        "Kick": 54,
        "Body": 55,
        "Control": 53,
        "Guard": 56,
        "Speed": 59,
        "Stamina": 56,
        "Guts": 65,
        "FP": 184,
        "TP": 161,
    },
    {
        "Name": "Tim Saunders",
        "Nickname": "Timmy",
        "Description": "Although small bodied/partitioned, he is a master of kung fu footwork insert.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/raimon/Timmy.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": special_moves[22],
        "SM2": special_moves[23],
        "SM3": special_moves[17],
        "SM4": special_moves[24],
        "Kick": 63,
        "Body": 76,
        "Control": 61,
        "Guard": 60,
        "Speed": 55,
        "Stamina": 48,
        "Guts": 58,
        "FP": 156,
        "TP": 149,
    },
    {
        "Name": "Maxwell Carson",
        "Nickname": "Max",
        "Description": "Beneath his cute exterior is a a multi-skilled sportsman.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/raimon/Max.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": special_moves[15],
        "SM2": special_moves[25],
        "SM3": special_moves[26],
        "SM4": special_moves[27],
        "Kick": 60,
        "Body": 56,
        "Control": 78,
        "Guard": 64,
        "Speed": 60,
        "Stamina": 56,
        "Guts": 62,    
        "FP": 156,
        "TP": 160,
    },
    {
        "Name": "Steve Grim",
        "Nickname": "Steve",
        "Description": "A twisting aerial move that fires up a mighty shot.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/raimon/Steve.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": special_moves[28],
        "SM2": special_moves[29],
        "SM3": special_moves[30],
        "SM4": special_moves[31],
        "Kick": 62,
        "Body": 64,
        "Control": 71,
        "Guard": 64,
        "Speed": 71,
        "Stamina": 71,
        "Guts": 71, 
        "FP": 154,
        "TP": 144,
    },
    {
        "Name": "Sam Kincaid",
        "Nickname": "Sam",
        "Description": "By twisting the body, this shot",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/raimon/Sam.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": special_moves[3],
        "SM2": special_moves[32],
        "SM3": special_moves[33],
        "SM4": special_moves[34],
        "Kick": 71,
        "Body": 57,
        "Control": 56,
        "Guard": 56,
        "Speed": 52,
        "Stamina": 56,
        "Guts": 76,
        "FP": 167,
        "TP": 136,
    },
    {
        "Name": "Kevin Dragonfly",
        "Nickname": "Kevin",
        "Description": "Raimon's fearsome goal scorer is really all heart.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/raimon/Kevin.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": special_moves[36],
        "SM2": special_moves[37],
        "SM3": special_moves[29],
        "SM4": special_moves[35],
        "Kick": 71,
        "Body": 60,
        "Control": 59,
        "Guard": 61,
        "Speed": 60,
        "Stamina": 64,
        "Guts": 70,
        "FP": 195,
        "TP": 144,
    },
    {
        "Name": "Axel Blaze",
        "Nickname": "Axel",
        "Description": "A cool transfer student renowned as a legendary striker.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/raimon/Axel.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": special_moves[38],
        "SM2": special_moves[39],
        "SM3": special_moves[40],
        "SM4": special_moves[15],
        "Kick": 79,
        "Body": 66,
        "Control": 76,
        "Guard": 64,
        "Speed": 72,
        "Stamina": 68,
        "Guts": 60,
        "FP": 200,
        "TP": 176,
    },
    {
        "Name": "Bobby Shearer",
        "Nickname": "Bobby",
        "Description": "Used to live in the USA. Behaves flippantly, but is deep-hearted.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/raimon/Bobby.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": special_moves[41],
        "SM2": special_moves[42],
        "SM3": special_moves[27],
        "SM4": special_moves[43],
        "Kick": 76,
        "Body": 61,
        "Control": 72,
        "Guard": 76,
        "Speed": 60,
        "Stamina": 72,
        "Guts": 72,
        "FP": 202,
        "TP": 176,
    },
    {
        "Name": "Erik Eagle",
        "Nickname": "Erik",
        "Description": "Silvia's friend from the USA. He was supposed to have died, but...",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/raimon/Erik.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": special_moves[44],
        "SM2": special_moves[45],
        "SM3": special_moves[26],
        "SM4": special_moves[46],
        "Kick": 79,
        "Body": 89,
        "Control": 99,
        "Guard": 94,
        "Speed": 79,
        "Stamina": 79,
        "Guts": 74,
        "FP": 154,
        "TP": 197,
    },
    {
        "Name": "William Glass",
        "Nickname": "Willy",
        "Description": "A highly popular student... or so he says!",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/raimon/Willy.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": special_moves[47],
        "SM2": special_moves[48],
        "SM3": special_moves[49],
        "SM4": special_moves[18],
        "Kick": 56,
        "Body": 51,
        "Control": 68,
        "Guard": 57,
        "Speed": 56,
        "Stamina": 53,
        "Guts": 60,
        "FP": 147,
        "TP": 168,
    },
    {
        "Name": "Nathan Jones",
        "Nickname": "Mask",
        "Description": "He is a bit dangerous with a grass cutter on the pitch.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/GK.png",
        "Sprite": "./images/players/ie1/occult/Mask.png",
        "Team": "Occult",
        "TeamSprite": "./images/emblems/Occult.png",
        "Game": "IE1",
        "SM1": special_moves[50],
        "SM2": special_moves[51],
        "SM3": special_moves[42],
        "SM4": special_moves[52],
        "Kick": 58,
        "Body": 56,
        "Control": 70,
        "Guard": 68,
        "Speed": 56,
        "Stamina": 60,
        "Guts": 68,
        "FP": 165,
        "TP": 156,
    },
    {
        "Name": "Ken Furan",
        "Nickname": "Franky",
        "Description": "Trying to create life, but biology is his worst class.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/occult/Franky.png",
        "Team": "Occult",
        "TeamSprite": "./images/emblems/Occult.png",
        "Game": "IE1",
        "SM1": special_moves[53],
        "SM2": special_moves[54],
        "SM3": special_moves[55],
        "SM4": special_moves[56],
        "Kick": 55,
        "Body": 59,
        "Control": 47,
        "Guard": 70,
        "Speed": 52,
        "Stamina": 61,
        "Guts": 48,
        "FP": 151,
        "TP": 156,
    },
    {
        "Name": "Russell Walk",
        "Nickname": "Styx",
        "Description": "After a spooky experience, even he is not sure if he is realy alive!",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/occult/Styx.png",
        "Team": "Occult",
        "TeamSprite": "./images/emblems/Occult.png",
        "Game": "IE1",
        "SM1": special_moves[57],
        "SM2": special_moves[58],
        "SM3": special_moves[59],
        "SM4": special_moves[60],
        "Kick": 60,
        "Body": 53,
        "Control": 60,
        "Guard": 52,
        "Speed": 63,
        "Stamina": 65,
        "Guts": 58,
        "FP": 140,
        "TP": 137,
    },
    {
        "Name": "Jason Jones",
        "Nickname": "Creepy",
        "Description": "He believes in ghosts an blames them for everything.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/occult/Creepy.png",
        "Team": "Occult",
        "TeamSprite": "./images/emblems/Occult.png",
        "Game": "IE1",
        "SM1": special_moves[61],
        "SM2": special_moves[62],
        "SM3": special_moves[57],
        "SM4": special_moves[33],
        "Kick": 52,
        "Body": 54,
        "Control": 57,
        "Guard": 57,
        "Speed": 60,
        "Stamina": 54,
        "Guts": 63,
        "FP": 151,
        "TP": 152,
    },
    {
        "Name": "Jason Jones",
        "Nickname": "Undead",
        "Description": "A dangerous player due to believing himself to be invincible.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/occult/Undead.png",
        "Team": "Occult",
        "TeamSprite": "./images/emblems/Occult.png",
        "Game": "IE1",
        "SM1": special_moves[61],
        "SM2": special_moves[60],
        "SM3": special_moves[59],
        "SM4": special_moves[13],
        "Kick": 52,
        "Body": 54,
        "Control": 57,
        "Guard": 57,
        "Speed": 60,
        "Stamina": 54,
        "Guts": 63,
        "FP": 151,
        "TP": 152,
    },
    {
        "Name": "Ray Mannings",
        "Nickname": "Jiangshi",
        "Description": "Although a bit stiff, he disturbs opponents by flying around them.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/occult/Jiangshi.png",
        "Team": "Occult",
        "TeamSprite": "./images/emblems/Occult.png",
        "Game": "IE1",
        "SM1": special_moves[57],
        "SM2": special_moves[59],
        "SM3": special_moves[62],
        "SM4": special_moves[51],
        "Kick": 55,
        "Body": 62,
        "Control": 60,
        "Guard": 52,
        "Speed": 56,
        "Stamina": 61,
        "Guts": 62,
        "FP": 145,
        "TP": 136,
    },
    {
        "Name": "Robert Mayer",
        "Nickname": "Mummy",
        "Description": "As he gets cold easily, he always keeps well wrapped up.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/occult/Mummy.png",
        "Team": "Occult",
        "TeamSprite": "./images/emblems/Occult.png",
        "Game": "IE1",
        "SM1": special_moves[57],
        "SM2": special_moves[63],
        "SM3": special_moves[64],
        "SM4": special_moves[51],
        "Kick": 54,
        "Body": 52,
        "Control": 60,
        "Guard": 52,
        "Speed": 62,
        "Stamina": 75,
        "Guts": 61,
        "FP": 187,
        "TP": 137,
    },
    {
        "Name": "Alexander Brave",
        "Nickname": "Grave",
        "Description": "People say he knows how to invoke catastrophic curses when angry.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/occult/Grave.png",
        "Team": "Occult",
        "TeamSprite": "./images/emblems/Occult.png",
        "Game": "IE1",
        "SM1": special_moves[59],
        "SM2": special_moves[13],
        "SM3": special_moves[60],
        "SM4": special_moves[65],
        "Kick": 57,
        "Body": 65,
        "Control": 60,
        "Guard": 52,
        "Speed": 71,
        "Stamina": 56,
        "Guts": 55,
        "FP": 180,
        "TP": 144,
    },
    {
        "Name": "Johan Tassman",
        "Nickname": "Talisman",
        "Description": "Uses his power to receive training from the ghosts of famous players.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/occult/Talisman.png",
        "Team": "Occult",
        "TeamSprite": "./images/emblems/Occult.png",
        "Game": "IE1",
        "SM1": special_moves[58],
        "SM2": special_moves[60],
        "SM3": special_moves[31],
        "SM4": special_moves[65],
        "Kick": 62,
        "Body": 64,
        "Control": 56,
        "Guard": 48,
        "Speed": 60,
        "Stamina": 62,
        "Guts": 63,
        "FP": 171,
        "TP": 165,
    },
    {
        "Name": "Troy Moon",
        "Nickname": "Wolfy",
        "Description": "Just a glance at a full moon gives 'Wolf Boy' violent tendencies.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/occult/Wolfy.png",
        "Team": "Occult",
        "TeamSprite": "./images/emblems/Occult.png",
        "Game": "IE1",
        "SM1": special_moves[62],
        "SM2": special_moves[60],
        "SM3": special_moves[75],
        "SM4": special_moves[76],
        "Kick": 61,
        "Body": 70,
        "Control": 77,
        "Guard": 52,
        "Speed": 79,
        "Stamina": 69,
        "Guts": 67,
        "FP": 211,
        "TP": 153,
    },
    {
        "Name": "Burt Wolf",
        "Nickname": "Blood",
        "Description": "Pale from always doing night shifts. Loves tomato juice.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/occult/Blood.png",
        "Team": "Occult",
        "TeamSprite": "./images/emblems/Occult.png",
        "Game": "IE1",
        "SM1": special_moves[60],
        "SM2": special_moves[62],
        "SM3": special_moves[63],
        "SM4": special_moves[35],
        "Kick": 68,
        "Body": 52,
        "Control": 52,
        "Guard": 51,
        "Speed": 56,
        "Stamina": 62,
        "Guts": 60,
        "FP": 184,
        "TP": 152,
    },
    {
        "Name": "Rob Crombie",
        "Nickname": "Zombie",
        "Description": "Doesn't feel a thing, no matter how badly injured.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/GK.png",
        "Sprite": "./images/players/ie1/occult/Zombie.png",
        "Team": "Occult",
        "TeamSprite": "./images/emblems/Occult.png",
        "Game": "IE1",
        "SM1": special_moves[77],
        "SM2": special_moves[61],
        "SM3": special_moves[58],
        "SM4": special_moves[78],
        "Kick": 47,
        "Body": 46,
        "Control": 50,
        "Guard": 40,
        "Speed": 51,
        "Stamina": 74,
        "Guts": 56,
        "FP": 200,
        "TP": 156,
    },
    {
        "Name": "Chuck Dollman",
        "Nickname": "Dollman",
        "Description": "Thinks he was made in a workshop and has no memories of the past.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/occult/Dollman.png",
        "Team": "Occult",
        "TeamSprite": "./images/emblems/Occult.png",
        "Game": "IE1",
        "SM1": special_moves[60],
        "SM2": special_moves[59],
        "SM3": special_moves[61],
        "SM4": special_moves[54],
        "Kick": 52,
        "Body": 53,
        "Control": 45,
        "Guard": 48,
        "Speed": 49,
        "Stamina": 53,
        "Guts": 55,
        "FP": 129,
        "TP": 104,
    },
    {
        "Name": "Uxley Allen",
        "Nickname": "Alien",
        "Description": "He believes in UFOs and watches out for them every night.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/occult/Alien.png",
        "Team": "Occult",
        "TeamSprite": "./images/emblems/Occult.png",
        "Game": "IE1",
        "SM1": special_moves[19],
        "SM2": special_moves[79],
        "SM3": special_moves[23],
        "SM4": special_moves[57],
        "Kick": 48,
        "Body": 51,
        "Control": 51,
        "Guard": 50,
        "Speed": 48,
        "Stamina": 55,
        "Guts": 44,
        "FP": 149,
        "TP": 112,
    },
    {
        "Name": "Phil Noir",
        "Nickname": "Noir",
        "Description": "An expert in black magic. He curses the opposition before every match.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/occult/Noir.png",
        "Team": "Occult",
        "TeamSprite": "./images/emblems/Occult.png",
        "Game": "IE1",
        "SM1": special_moves[59],
        "SM2": special_moves[79],
        "SM3": special_moves[61],
        "SM4": special_moves[80],
        "Kick": 52,
        "Body": 45,
        "Control": 48,
        "Guard": 52,
        "Speed": 52,
        "Stamina": 58,
        "Guts": 45,
        "FP": 121,
        "TP": 120,
    },
    {
        "Name": "Mick Askley",
        "Nickname": "Ghost",
        "Description": "He believes he is not human and hides behind a mysterious mask.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/occult/Ghost.png",
        "Team": "Occult",
        "TeamSprite": "./images/emblems/Occult.png",
        "Game": "IE1",
        "SM1": special_moves[57],
        "SM2": special_moves[35],
        "SM3": special_moves[78],
        "SM4": special_moves[51],
        "Kick": 55,
        "Body": 50,
        "Control": 54,
        "Guard": 44,
        "Speed": 48,
        "Stamina": 56,
        "Guts": 54,
        "FP": 143,
        "TP": 100,
    },
    {
        "Name": "Herman Muller",
        "Nickname": "Muller",
        "Description": "Learnt to play football through playing video games.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/GK.png",
        "Sprite": "./images/players/ie1/inazuma_kfc/Muller.png",
        "Team": "Inazuma KFC",
        "TeamSprite": "./images/emblems/Inazuma_KFC.png",
        "Game": "IE1",
        "SM1": special_moves[81],
        "SM2": special_moves[54],
        "SM3": special_moves[33],
        "SM4": special_moves[82],
        "Kick": 40,
        "Body": 50,
        "Control": 44,
        "Guard": 47,
        "Speed": 44,
        "Stamina": 46,
        "Guts": 45,
        "FP": 143,
        "TP": 109,
    },
    {
        "Name": "Keth Claus",
        "Nickname": "Claus",
        "Description": "Used to be a gang leader, but now takes care of his team members.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/inazuma_kfc/Claus.png",
        "Team": "Inazuma KFC",
        "TeamSprite": "./images/emblems/Inazuma_KFC.png",
        "Game": "IE1",
        "SM1": special_moves[83],
        "SM2": special_moves[84],
        "SM3": special_moves[20],
        "SM4": special_moves[11],
        "Kick": 41,
        "Body": 41,
        "Control": 48,
        "Guard": 40,
        "Speed": 60,
        "Stamina": 40,
        "Guts": 46,
        "FP": 112,
        "TP": 84,
    },
    {
        "Name": "Robert Silver",
        "Nickname": "Silver",
        "Description": "He's always dreaming up new pranks, which always gets him into trouble.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/inazuma_kfc/Silver.png",
        "Team": "Inazuma KFC",
        "TeamSprite": "./images/emblems/Inazuma_KFC.png",
        "Game": "IE1",
        "SM1": special_moves[14],
        "SM2": special_moves[32],
        "SM3": special_moves[33],
        "SM4": special_moves[11],
        "Kick": 46,
        "Body": 41,
        "Control": 51,
        "Guard": 44,
        "Speed": 41,
        "Stamina": 48,
        "Guts": 44,
        "FP": 125,
        "TP": 73,
    },
    {
        "Name": "Izzy Island",
        "Nickname": "Izzy",
        "Description": "Studies football theory. Known for asking adults difficult questions.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/inazuma_kfc/Izzy.png",
        "Team": "Inazuma KFC",
        "TeamSprite": "./images/emblems/Inazuma_KFC.png",
        "Game": "IE1",
        "SM1": special_moves[22],
        "SM2": special_moves[48],
        "SM3": special_moves[47],
        "SM4": special_moves[64],
        "Kick": 42,
        "Body": 40,
        "Control": 48,
        "Guard": 41,
        "Speed": 41,
        "Stamina": 48,
        "Guts": 44,
        "FP": 136,
        "TP": 65,
    },
    {
        "Name": "Sothern Newman",
        "Nickname": "Newman",
        "Description": "Practises relentlessly, but puts on weight by eating too many snacks.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/inazuma_kfc/Newman.png",
        "Team": "Inazuma KFC",
        "TeamSprite": "./images/emblems/Inazuma_KFC.png",
        "Game": "IE1",
        "SM1": special_moves[6],
        "SM2": special_moves[7],
        "SM3": special_moves[81],
        "SM4": special_moves[85],
        "Kick": 45,
        "Body": 44,
        "Control": 48,
        "Guard": 60,
        "Speed": 43,
        "Stamina": 49,
        "Guts": 47,
        "FP": 127,
        "TP": 60,
    },
    {
        "Name": "Irwin Hall",
        "Nickname": "Hall",
        "Description": "Worried about his height, he drinks milk daily to make his bones grow.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/inazuma_kfc/Hall.png",
        "Team": "Inazuma KFC",
        "TeamSprite": "./images/emblems/Inazuma_KFC.png",
        "Game": "IE1",
        "SM1": special_moves[18],
        "SM2": special_moves[32],
        "SM3": special_moves[86],
        "SM4": special_moves[11],
        "Kick": 40,
        "Body": 48,
        "Control": 51,
        "Guard": 43,
        "Speed": 41,
        "Stamina": 40,
        "Guts": 41,
        "FP": 162,
        "TP": 69,
    },
    {
        "Name": "Taylor Higgins",
        "Nickname": "Higgins",
        "Description": "A mother's boy who always falters if his mum isn't in the crowd.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/inazuma_kfc/Higgins.png",
        "Team": "Inazuma KFC",
        "TeamSprite": "./images/emblems/Inazuma_KFC.png",
        "Game": "IE1",
        "SM1": special_moves[18],
        "SM2": special_moves[10],
        "SM3": special_moves[29],
        "SM4": special_moves[34],
        "Kick": 44,
        "Body": 43,
        "Control": 50,
        "Guard": 48,
        "Speed": 40,
        "Stamina": 48,
        "Guts": 40,
        "FP": 134,
        "TP": 65,
    },
    {
        "Name": "Jamie Cool",
        "Nickname": "Cool",
        "Description": "Has pride in his speed and often attends athletic meets.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/inazuma_kfc/Cool.png",
        "Team": "Inazuma KFC",
        "TeamSprite": "./images/emblems/Inazuma_KFC.png",
        "Game": "IE1",
        "SM1": special_moves[87],
        "SM2": special_moves[14],
        "SM3": special_moves[15],
        "SM4": special_moves[65],
        "Kick": 47,
        "Body": 40,
        "Control": 44,
        "Guard": 48,
        "Speed": 52,
        "Stamina": 52,
        "Guts": 51,
        "FP": 162,
        "TP": 76,
    },
    {
        "Name": "Hans Randall",
        "Nickname": "Randall",
        "Description": "A rising star who has taken part in the national junior championships.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/inazuma_kfc/Randall.png",
        "Team": "Inazuma KFC",
        "TeamSprite": "./images/emblems/Inazuma_KFC.png",
        "Game": "IE1",
        "SM1": special_moves[83],
        "SM2": special_moves[19],
        "SM3": special_moves[29],
        "SM4": special_moves[36],
        "Kick": 64,
        "Body": 40,
        "Control": 40,
        "Guard": 51,
        "Speed": 48,
        "Stamina": 56,
        "Guts": 44,
        "FP": 169,
        "TP": 65,
    },
    {
        "Name": "Michael Riverside",
        "Nickname": "Riverside",
        "Description": "He became a footballer by copying all of his heroes' moves.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/inazuma_kfc/Riverside.png",
        "Team": "Inazuma KFC",
        "TeamSprite": "./images/emblems/Inazuma_KFC.png",
        "Game": "IE1",
        "SM1": special_moves[83],
        "SM2": special_moves[15],
        "SM3": special_moves[88],
        "SM4": special_moves[21],
        "Kick": 51,
        "Body": 46,
        "Control": 50,
        "Guard": 49,
        "Speed": 40,
        "Stamina": 43,
        "Guts": 48,
        "FP": 138,
        "TP": 77,
    },
    {
        "Name": "Millie Moonlight",
        "Nickname": "Millie",
        "Description": "This team-leading girl is the daughter of a restaurant owner.",
        "Gender": "./images/genders/Female.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/inazuma_kfc/Millie.png",
        "Team": "Inazuma KFC",
        "TeamSprite": "./images/emblems/Inazuma_KFC.png",
        "Game": "IE1",
        "SM1": special_moves[19],
        "SM2": special_moves[18],
        "SM3": special_moves[87],
        "SM4": special_moves[89],
        "Kick": 44,
        "Body": 40,
        "Control": 60,
        "Guard": 42,
        "Speed": 51,
        "Stamina": 40,
        "Guts": 46,
        "FP": 167,
        "TP": 148,
    },
    {
        "Name": "Bart Grantham",
        "Nickname": "Grantham",
        "Description": "Loves aeroplanes and dreams of becoming a pilot one day.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/GK.png",
        "Sprite": "./images/players/ie1/inazuma_kfc/Grantham.png",
        "Team": "Inazuma KFC",
        "TeamSprite": "./images/emblems/Inazuma_KFC.png",
        "Game": "IE1",
        "SM1": special_moves[18],
        "SM2": special_moves[22],
        "SM3": special_moves[90],
        "SM4": special_moves[85],
        "Kick": 38,
        "Body": 35,
        "Control": 29,
        "Guard": 66,
        "Speed": 28,
        "Stamina": 29,
        "Guts": 64,
        "FP": 101,
        "TP": 180,
    },
    {
        "Name": "Karl Blue",
        "Nickname": "Karl",
        "Description": "Likes teasing people, especially if he can knock them down a peg or two.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/inazuma_kfc/Karl.png",
        "Team": "Inazuma KFC",
        "TeamSprite": "./images/emblems/Inazuma_KFC.png",
        "Game": "IE1",
        "SM1": special_moves[14],
        "SM2": special_moves[59],
        "SM3": special_moves[33],
        "SM4": special_moves[11],
        "Kick": 46,
        "Body": 48,
        "Control": 47,
        "Guard": 44,
        "Speed": 51,
        "Stamina": 46,
        "Guts": 48,
        "FP": 114,
        "TP": 76,
    },
    {
        "Name": "Theakston Plank",
        "Nickname": "Plank",
        "Description": "No matter what people say, this kid is two players short of a team.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/inazuma_kfc/Plank.png",
        "Team": "Inazuma KFC",
        "TeamSprite": "./images/emblems/Inazuma_KFC.png",
        "Game": "IE1",
        "SM1": special_moves[19],
        "SM2": special_moves[22],
        "SM3": special_moves[44],
        "SM4": special_moves[23],
        "Kick": 48,
        "Body": 50,
        "Control": 42,
        "Guard": 45,
        "Speed": 58,
        "Stamina": 41,
        "Guts": 51,
        "FP": 121,
        "TP": 80,
    },
    {
        "Name": "Ken Cake",
        "Nickname": "Cake",
        "Description": "A cake fiend whose favourite haunt is an all-you-can-eat cake buffet.",
        "Gender": "./images/genders/Female.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/inazuma_kfc/Cake.png",
        "Team": "Inazuma KFC",
        "TeamSprite": "./images/emblems/Inazuma_KFC.png",
        "Game": "IE1",
        "SM1": special_moves[25],
        "SM2": special_moves[77],
        "SM3": special_moves[78],
        "SM4": special_moves[91],
        "Kick": 49,
        "Body": 40,
        "Control": 40,
        "Guard": 40,
        "Speed": 51,
        "Stamina": 49,
        "Guts": 46,
        "FP": 123,
        "TP": 88,
    },
    {
        "Name": "Mitch Grumble",
        "Nickname": "Grumble",
        "Description": "The runt of a family big enough to make a team of their own.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/inazuma_kfc/Grumble.png",
        "Team": "Inazuma KFC",
        "TeamSprite": "./images/emblems/Inazuma_KFC.png",
        "Game": "IE1",
        "SM1": special_moves[26],
        "SM2": special_moves[29],
        "SM3": special_moves[58],
        "SM4": special_moves[13],
        "Kick": 48,
        "Body": 48,
        "Control": 43,
        "Guard": 48,
        "Speed": 40,
        "Stamina": 46,
        "Guts": 41,
        "FP": 110,
        "TP": 65,
    },
    {
        "Name": "Joe Ingram",
        "Nickname": "Ingram",
        "Description": "No matter the situation, he always has a joke to lighten the mood.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/GK.png",
        "Sprite": "./images/players/ie1/umbrella/Ingram.png",
        "Team": "Umbrella",
        "TeamSprite": "./images/emblems/Umbrella.png",
        "Game": "IE1",
        "SM1": special_moves[92],
        "SM2": special_moves[44],
        "SM3": special_moves[52],
        "SM4": special_moves[27],
        "Kick": 44,
        "Body": 71,
        "Control": 52,
        "Guard": 74,
        "Speed": 47,
        "Stamina": 57,
        "Guts": 78,
        "FP": 149,
        "TP": 113,
    },
    {
        "Name": "Kendall Sefton",
        "Nickname": "Sefton",
        "Description": "He practises tai chi to warm up before matches.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/umbrella/Sefton.png",
        "Team": "Umbrella",
        "TeamSprite": "./images/emblems/Umbrella.png",
        "Game": "IE1",
        "SM1": special_moves[45],
        "SM2": special_moves[22],
        "SM3": special_moves[23],
        "SM4": special_moves[64],
        "Kick": 53,
        "Body": 49,
        "Control": 61,
        "Guard": 54,
        "Speed": 67,
        "Stamina": 54,
        "Guts": 55,
        "FP": 151,
        "TP": 109,
    },
    {
        "Name": "Jason Strike",
        "Nickname": "Strike",
        "Description": "Loves exercise so much, his home is practically a gym.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/umbrella/Strike.png",
        "Team": "Umbrella",
        "TeamSprite": "./images/emblems/Umbrella.png",
        "Game": "IE1",
        "SM1": special_moves[15],
        "SM2": special_moves[28],
        "SM3": special_moves[42],
        "SM4": special_moves[91],
        "Kick": 48,
        "Body": 50,
        "Control": 64,
        "Guard": 47,
        "Speed": 56,
        "Stamina": 51,
        "Guts": 53,
        "FP": 132,
        "TP": 109,
    },
    {
        "Name": "Norman Porter",
        "Nickname": "Porter",
        "Description": "He's always willing to lend anyone a hand with heavy luggage.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/umbrella/Porter.png",
        "Team": "Umbrella",
        "TeamSprite": "./images/emblems/Umbrella.png",
        "Game": "IE1",
        "SM1": special_moves[41],
        "SM2": special_moves[78],
        "SM3": special_moves[6],
        "SM4": special_moves[35],
        "Kick": 45,
        "Body": 56,
        "Control": 44,
        "Guard": 60,
        "Speed": 44,
        "Stamina": 52,
        "Guts": 46,
        "FP": 145,
        "TP": 112,
    },
    {
        "Name": "Maxwell Claus",
        "Nickname": "Chops",
        "Description": "Superstitiously eats pork chops before every match.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/umbrella/Chops.png",
        "Team": "Umbrella",
        "TeamSprite": "./images/emblems/Umbrella.png",
        "Game": "IE1",
        "SM1": special_moves[10],
        "SM2": special_moves[42],
        "SM3": special_moves[20],
        "SM4": special_moves[30],
        "Kick": 62,
        "Body": 53,
        "Control": 55,
        "Guard": 44,
        "Speed": 53,
        "Stamina": 55,
        "Guts": 49,
        "FP": 136,
        "TP": 120,
    },
    {
        "Name": "Bruce Chaney",
        "Nickname": "Chaney",
        "Description": "Practises in car parks at night, using headlights for floodlights.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/umbrella/Chaney.png",
        "Team": "Umbrella",
        "TeamSprite": "./images/emblems/Umbrella.png",
        "Game": "IE1",
        "SM1": special_moves[3],
        "SM2": special_moves[93],
        "SM3": special_moves[94],
        "SM4": special_moves[27],
        "Kick": 46,
        "Body": 48,
        "Control": 48,
        "Guard": 45,
        "Speed": 66,
        "Stamina": 48,
        "Guts": 49,
        "FP": 136,
        "TP": 121,
    },
    {
        "Name": "Leroy Rhymes",
        "Nickname": "Rhymes",
        "Description": "Trains his balance by practising on a unicycle he got in primary school.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/umbrella/Rhymes.png",
        "Team": "Umbrella",
        "TeamSprite": "./images/emblems/Umbrella.png",
        "Game": "IE1",
        "SM1": special_moves[18],
        "SM2": special_moves[22],
        "SM3": special_moves[21],
        "SM4": special_moves[35],
        "Kick": 47,
        "Body": 48,
        "Control": 52,
        "Guard": 53,
        "Speed": 46,
        "Stamina": 45,
        "Guts": 48,
        "FP": 140,
        "TP": 140,
    },
    {
        "Name": "Mildford Scott",
        "Nickname": "Scott",
        "Description": "Keeps up-to-date on world football using football sites and magazines.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/umbrella/Scott.png",
        "Team": "Umbrella",
        "TeamSprite": "./images/emblems/Umbrella.png",
        "Game": "IE1",
        "SM1": special_moves[47],
        "SM2": special_moves[62],
        "SM3": special_moves[33],
        "SM4": special_moves[48],
        "Kick": 44,
        "Body": 52,
        "Control": 47,
        "Guard": 50,
        "Speed": 55,
        "Stamina": 52,
        "Guts": 44,
        "FP": 129,
        "TP": 109,
    },
    {
        "Name": "Lou Edmonds",
        "Nickname": "Edmonds",
        "Description": "Always seen running around helping out at his parents' restaurant.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/umbrella/Edmonds.png",
        "Team": "Umbrella",
        "TeamSprite": "./images/emblems/Umbrella.png",
        "Game": "IE1",
        "SM1": special_moves[83],
        "SM2": special_moves[44],
        "SM3": special_moves[40],
        "SM4": special_moves[32],
        "Kick": 60,
        "Body": 68,
        "Control": 45,
        "Guard": 51,
        "Speed": 44,
        "Stamina": 54,
        "Guts": 71,
        "FP": 143,
        "TP": 124,
    },
    {
        "Name": "Cameron Morefield",
        "Nickname": "Morefield",
        "Description": "Turned to football after hurting his wrist playing semi-pro tennis.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/umbrella/Morefield.png",
        "Team": "Umbrella",
        "TeamSprite": "./images/emblems/Umbrella.png",
        "Game": "IE1",
        "SM1": special_moves[14],
        "SM2": special_moves[44],
        "SM3": special_moves[93],
        "SM4": special_moves[31],
        "Kick": 59,
        "Body": 56,
        "Control": 58,
        "Guard": 52,
        "Speed": 48,
        "Stamina": 52,
        "Guts": 72,
        "FP": 167,
        "TP": 129,
    },
    {
        "Name": "Greg Bernard",
        "Nickname": "Cyborg",
        "Description": "He plays so robotically that he was given the nickname 'Cyborg'.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/umbrella/Cyborg.png",
        "Team": "Umbrella",
        "TeamSprite": "./images/emblems/Umbrella.png",
        "Game": "IE1",
        "SM1": special_moves[95],
        "SM2": special_moves[48],
        "SM3": special_moves[29],
        "SM4": special_moves[96],
        "Kick": 49,
        "Body": 55,
        "Control": 63,
        "Guard": 51,
        "Speed": 51,
        "Stamina": 56,
        "Guts": 65,
        "FP": 123,
        "TP": 165,
    },
    {
        "Name": "Peter Banker",
        "Nickname": "Banker",
        "Description": "Believes his tactics - once perfected - revolutionise football.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/GK.png",
        "Sprite": "./images/players/ie1/umbrella/Banker.png",
        "Team": "Umbrella",
        "TeamSprite": "./images/emblems/Umbrella.png",
        "Game": "IE1",
        "SM1": special_moves[44],
        "SM2": special_moves[19],
        "SM3": special_moves[60],
        "SM4": special_moves[84],
        "Kick": 50,
        "Body": 45,
        "Control": 51,
        "Guard": 63,
        "Speed": 50,
        "Stamina": 45,
        "Guts": 75,
        "FP": 138,
        "TP": 122,
    },
    {
        "Name": "Saul Tunk",
        "Nickname": "Tunk",
        "Description": "Not a team player, but good at smoothing over ruffled feathers.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/umbrella/Tunk.png",
        "Team": "Umbrella",
        "TeamSprite": "./images/emblems/Umbrella.png",
        "Game": "IE1",
        "SM1": special_moves[25],
        "SM2": special_moves[59],
        "SM3": special_moves[97],
        "SM4": special_moves[88],
        "Kick": 55,
        "Body": 53,
        "Control": 44,
        "Guard": 62,
        "Speed": 55,
        "Stamina": 47,
        "Guts": 54,
        "FP": 145,
        "TP": 109,
    },
    {
        "Name": "Alan Most",
        "Nickname": "Most",
        "Description": "He is unable to succeed at anything without his parents' advice.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/umbrella/Most.png",
        "Team": "Umbrella",
        "TeamSprite": "./images/emblems/Umbrella.png",
        "Game": "IE1",
        "SM1": special_moves[83],
        "SM2": special_moves[7],
        "SM3": special_moves[77],
        "SM4": special_moves[81],
        "Kick": 65,
        "Body": 60,
        "Control": 60,
        "Guard": 68,
        "Speed": 63,
        "Stamina": 61,
        "Guts": 64,
        "FP": 191,
        "TP": 165,
    },
    {
        "Name": "Paul Caperock",
        "Nickname": "Caperock",
        "Description": "A real football maniac. He eats, sleeps and breathes football.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/umbrella/Caperock.png",
        "Team": "Umbrella",
        "TeamSprite": "./images/emblems/Umbrella.png",
        "Game": "IE1",
        "SM1": special_moves[41],
        "SM2": special_moves[90],
        "SM3": special_moves[42],
        "SM4": special_moves[94],
        "Kick": 54,
        "Body": 50,
        "Control": 46,
        "Guard": 45,
        "Speed": 58,
        "Stamina": 48,
        "Guts": 53,
        "FP": 140,
        "TP": 113,
    },
    {
        "Name": "Julius Molehill",
        "Nickname": "Molehill",
        "Description": "Has a complex about being small and compensates with a big personality.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/umbrella/Molehill.png",
        "Team": "Umbrella",
        "TeamSprite": "./images/emblems/Umbrella.png",
        "Game": "IE1",
        "SM1": special_moves[28],
        "SM2": special_moves[14],
        "SM3": special_moves[12],
        "SM4": special_moves[34],
        "Kick": 53,
        "Body": 48,
        "Control": 68,
        "Guard": 48,
        "Speed": 55,
        "Stamina": 49,
        "Guts": 46,
        "FP": 123,
        "TP": 113,
    },
    {
        "Name": "Charlie Boardfield",
        "Nickname": "Boar",
        "Description": "He runs at the ball like a boar to truffles.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/GK.png",
        "Sprite": "./images/players/ie1/wild/Boar.png",
        "Team": "Wild",
        "TeamSprite": "./images/emblems/Wild.png",
        "Game": "IE1",
        "SM1": special_moves[76],
        "SM2": special_moves[98],
        "SM3": special_moves[55],
        "SM4": special_moves[7],
        "Kick": 68,
        "Body": 44,
        "Control": 44,
        "Guard": 69,
        "Speed": 60,
        "Stamina": 62,
        "Guts": 69,
        "FP": 217,
        "TP": 100,
    },
    {
        "Name": "Hugo Tallgeese",
        "Nickname": "Chicken",
        "Description": "Charges repeatedly, just like a stubborn rooster pecking around.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/wild/Chicken.png",
        "Team": "Wild",
        "TeamSprite": "./images/emblems/Wild.png",
        "Game": "IE1",
        "SM1": special_moves[83],
        "SM2": special_moves[87],
        "SM3": special_moves[65],
        "SM4": special_moves[99],
        "Kick": 44,
        "Body": 52,
        "Control": 56,
        "Guard": 46,
        "Speed": 64,
        "Stamina": 67,
        "Guts": 54,
        "FP": 189,
        "TP": 101,
    },
    {
        "Name": "Wilson Fishman",
        "Nickname": "Fishman",
        "Description": "An expert on marine life, but can't swim. Often skips swimming classes.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/wild/Fishman.png",
        "Team": "Wild",
        "TeamSprite": "./images/emblems/Wild.png",
        "Game": "IE1",
        "SM1": special_moves[15],
        "SM2": special_moves[45],
        "SM3": special_moves[18],
        "SM4": special_moves[21],
        "Kick": 52,
        "Body": 64,
        "Control": 51,
        "Guard": 51,
        "Speed": 51,
        "Stamina": 62,
        "Guts": 51,
        "FP": 167,
        "TP": 113,
    },
    {
        "Name": "Peter Johnson",
        "Nickname": "Toad",
        "Description": "Superb at jumping. His room is full of frog-related goods.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/wild/Toad.png",
        "Team": "Wild",
        "TeamSprite": "./images/emblems/Wild.png",
        "Game": "IE1",
        "SM1": special_moves[41],
        "SM2": special_moves[83],
        "SM3": special_moves[33],
        "SM4": special_moves[28],
        "Kick": 48,
        "Body": 52,
        "Control": 48,
        "Guard": 48,
        "Speed": 54,
        "Stamina": 57,
        "Guts": 50,
        "FP": 167,
        "TP": 109,
    },
    {
        "Name": "Leonard O'Shea",
        "Nickname": "Lion",
        "Description": "He doesn't take any backchat and guards his title as Wild's king.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/wild/Lion.png",
        "Team": "Wild",
        "TeamSprite": "./images/emblems/Wild.png",
        "Game": "IE1",
        "SM1": special_moves[7],
        "SM2": special_moves[78],
        "SM3": special_moves[56],
        "SM4": special_moves[21],
        "Kick": 78,
        "Body": 52,
        "Control": 47,
        "Guard": 64,
        "Speed": 55,
        "Stamina": 69,
        "Guts": 68,
        "FP": 195,
        "TP": 113,
    },
    {
        "Name": "Cham Lion",
        "Nickname": "Chameleon",
        "Description": "He is able to steal the ball before opponents know he is even there.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/wild/Chameleon.png",
        "Team": "Wild",
        "TeamSprite": "./images/emblems/Wild.png",
        "Game": "IE1",
        "SM1": special_moves[15],
        "SM2": special_moves[12],
        "SM3": special_moves[11],
        "SM4": special_moves[58],
        "Kick": 44,
        "Body": 45,
        "Control": 45,
        "Guard": 55,
        "Speed": 53,
        "Stamina": 60,
        "Guts": 48,
        "FP": 176,
        "TP": 101,
    },
    {
        "Name": "Steve Eagle",
        "Nickname": "Eagle",
        "Description": "He catches opponents' movements with his eagle-eyes.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/wild/Eagle.png",
        "Team": "Wild",
        "TeamSprite": "./images/emblems/Wild.png",
        "Game": "IE1",
        "SM1": special_moves[100],
        "SM2": special_moves[87],
        "SM3": special_moves[26],
        "SM4": special_moves[99],
        "Kick": 61,
        "Body": 68,
        "Control": 62,
        "Guard": 52,
        "Speed": 68,
        "Stamina": 71,
        "Guts": 68,
        "FP": 193,
        "TP": 148,
    },
    {
        "Name": "Bruce Monkey",
        "Nickname": "Monkey",
        "Description": "He may be small, but his acrobatics put his opponents to shame.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/wild/Monkey.png",
        "Team": "Wild",
        "TeamSprite": "./images/emblems/Wild.png",
        "Game": "IE1",
        "SM1": special_moves[20],
        "SM2": special_moves[88],
        "SM3": special_moves[10],
        "SM4": special_moves[75],
        "Kick": 54,
        "Body": 64,
        "Control": 51,
        "Guard": 48,
        "Speed": 53,
        "Stamina": 52,
        "Guts": 54,
        "FP": 184,
        "TP": 100,
    },
    {
        "Name": "Gary Lancaster",
        "Nickname": "Gorilla",
        "Description": "Beats the ball into the goal with his ape-like size and strength.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/wild/Gorilla.png",
        "Team": "Wild",
        "TeamSprite": "./images/emblems/Wild.png",
        "Game": "IE1",
        "SM1": special_moves[88],
        "SM2": special_moves[7],
        "SM3": special_moves[32],
        "SM4": special_moves[94],
        "Kick": 78,
        "Body": 66,
        "Control": 49,
        "Guard": 64,
        "Speed": 54,
        "Stamina": 52,
        "Guts": 67,
        "FP": 191,
        "TP": 108,
    },
    {
        "Name": "Harry Snake",
        "Nickname": "Snake",
        "Description": "Once he has the ball wrapped up, he doesn't release it.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/wild/Snake.png",
        "Team": "Wild",
        "TeamSprite": "./images/emblems/Wild.png",
        "Game": "IE1",
        "SM1": special_moves[95],
        "SM2": special_moves[29],
        "SM3": special_moves[91],
        "SM4": special_moves[64],
        "Kick": 55,
        "Body": 63,
        "Control": 62,
        "Guard": 49,
        "Speed": 55,
        "Stamina": 65,
        "Guts": 45,
        "FP": 184,
        "TP": 112,
    },
    {
        "Name": "Adrian Speed",
        "Nickname": "Cheetah",
        "Description": "Capable of charging down opponents at over 10 m/s.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/wild/Cheetah.png",
        "Team": "Wild",
        "TeamSprite": "./images/emblems/Wild.png",
        "Game": "IE1",
        "SM1": special_moves[88],
        "SM2": special_moves[83],
        "SM3": special_moves[93],
        "SM4": special_moves[24],
        "Kick": 63,
        "Body": 47,
        "Control": 69,
        "Guard": 55,
        "Speed": 79,
        "Stamina": 42,
        "Guts": 47,
        "FP": 195,
        "TP": 133,
    },
    {
        "Name": "Chad Bullford",
        "Nickname": "Bullford",
        "Description": "A complete glutton who goes into a rage if he runs out of food.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/GK.png",
        "Sprite": "./images/players/ie1/wild/Bullford.png",
        "Team": "Wild",
        "TeamSprite": "./images/emblems/Wild.png",
        "Game": "IE1",
        "SM1": special_moves[78],
        "SM2": special_moves[90],
        "SM3": special_moves[76],
        "SM4": special_moves[77],
        "Kick": 41,
        "Body": 68,
        "Control": 48,
        "Guard": 77,
        "Speed": 31,
        "Stamina": 51,
        "Guts": 64,
        "FP": 171,
        "TP": 174,
    },
    {
        "Name": "Alan Coe",
        "Nickname": "Koala",
        "Description": "He feels more at home in the trees than on the ground.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/wild/Koala.png",
        "Team": "Wild",
        "TeamSprite": "./images/emblems/Wild.png",
        "Game": "IE1",
        "SM1": special_moves[88],
        "SM2": special_moves[20],
        "SM3": special_moves[21],
        "SM4": special_moves[26],
        "Kick": 52,
        "Body": 45,
        "Control": 53,
        "Guard": 51,
        "Speed": 48,
        "Stamina": 46,
        "Guts": 49,
        "FP": 132,
        "TP": 112,
    },
    {
        "Name": "Philip Anders",
        "Nickname": "Panda",
        "Description": "Appears kind and handsome at first glance, but has a brutal character.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/wild/Panda.png",
        "Team": "Wild",
        "TeamSprite": "./images/emblems/Wild.png",
        "Game": "IE1",
        "SM1": special_moves[41],
        "SM2": special_moves[18],
        "SM3": special_moves[23],
        "SM4": special_moves[97],
        "Kick": 52,
        "Body": 51,
        "Control": 48,
        "Guard": 52,
        "Speed": 52,
        "Stamina": 51,
        "Guts": 46,
        "FP": 123,
        "TP": 132,
    },
    {
        "Name": "Rocky Rackham",
        "Nickname": "Raccoon",
        "Description": "Appreciates good food, even if it has come straight out of the bin!",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/wild/Raccoon.png",
        "Team": "Wild",
        "TeamSprite": "./images/emblems/Wild.png",
        "Game": "IE1",
        "SM1": special_moves[7],
        "SM2": special_moves[3],
        "SM3": special_moves[78],
        "SM4": special_moves[11],
        "Kick": 53,
        "Body": 53,
        "Control": 53,
        "Guard": 44,
        "Speed": 51,
        "Stamina": 44,
        "Guts": 47,
        "FP": 123,
        "TP": 121,
    },
    {
        "Name": "Matt Mouseman",
        "Nickname": "Mouseman",
        "Description": "Loves cheese. Even eats smelly blue cheeses that others leave behind!",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/wild/Mouseman.png",
        "Team": "Wild",
        "TeamSprite": "./images/emblems/Wild.png",
        "Game": "IE1",
        "SM1": special_moves[33],
        "SM2": special_moves[32],
        "SM3": special_moves[58],
        "SM4": special_moves[12],
        "Kick": 42,
        "Body": 50,
        "Control": 52,
        "Guard": 44,
        "Speed": 79,
        "Stamina": 54,
        "Guts": 45,
        "FP": 158,
        "TP": 112,
    },
    {
        "Name": "Thomas Feldt",
        "Nickname": "Feldt",
        "Description": "Follows instruction well, but lost all emotion after brainwashing.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/GK.png",
        "Sprite": "./images/players/ie1/brainwashing/Feldt.png",
        "Team": "Brainwashing",
        "TeamSprite": "./images/emblems/Brainwashing.png",
        "Game": "IE1",
        "SM1": special_moves[101],
        "SM2": special_moves[54],
        "SM3": special_moves[55],
        "SM4": special_moves[47],
        "Kick": 75,
        "Body": 69,
        "Control": 68,
        "Guard": 76,
        "Speed": 75,
        "Stamina": 78,
        "Guts": 76,
        "FP": 206,
        "TP": 177,
    },
    {
        "Name": "Harry Leading",
        "Nickname": "Leading",
        "Description": "Took up football to get famous, but forgot it all after 'conditioning'.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/brainwashing/Leading.png",
        "Team": "Brainwashing",
        "TeamSprite": "./images/emblems/Brainwashing.png",
        "Game": "IE1",
        "SM1": special_moves[47],
        "SM2": special_moves[11],
        "SM3": special_moves[48],
        "SM4": special_moves[96],
        "Kick": 52,
        "Body": 52,
        "Control": 44,
        "Guard": 47,
        "Speed": 50,
        "Stamina": 52,
        "Guts": 48,
        "FP": 140,
        "TP": 112,
    },
    {
        "Name": "Terry Stronger",
        "Nickname": "Stronger",
        "Description": "His augment makes him prone to losing his will.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/brainwashing/Stronger.png",
        "Team": "Brainwashing",
        "TeamSprite": "./images/emblems/Brainwashing.png",
        "Game": "IE1",
        "SM1": special_moves[47],
        "SM2": special_moves[48],
        "SM3": special_moves[79],
        "SM4": special_moves[23],
        "Kick": 44,
        "Body": 46,
        "Control": 46,
        "Guard": 52,
        "Speed": 47,
        "Stamina": 52,
        "Guts": 52,
        "FP": 144,
        "TP": 121,
    },
    {
        "Name": "Philip Marvel",
        "Nickname": "Marvel",
        "Description": "Brainwashing implanted fear in him. He now overreacts to all surprises.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/brainwashing/Marvel.png",
        "Team": "Brainwashing",
        "TeamSprite": "./images/emblems/Brainwashing.png",
        "Game": "IE1",
        "SM1": special_moves[47],
        "SM2": special_moves[93],
        "SM3": special_moves[48],
        "SM4": special_moves[35],
        "Kick": 44,
        "Body": 53,
        "Control": 52,
        "Guard": 48,
        "Speed": 49,
        "Stamina": 50,
        "Guts": 51,
        "FP": 143,
        "TP": 108,
    },
    {
        "Name": "Noel Good",
        "Nickname": "Good",
        "Description": "Flaunts the rules with every move since being brainwashed.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/brainwashing/Good.png",
        "Team": "Brainwashing",
        "TeamSprite": "./images/emblems/Brainwashing.png",
        "Game": "IE1",
        "SM1": special_moves[47],
        "SM2": special_moves[48],
        "SM3": special_moves[79],
        "SM4": special_moves[98],
        "Kick": 44,
        "Body": 44,
        "Control": 48,
        "Guard": 55,
        "Speed": 44,
        "Stamina": 48,
        "Guts": 45,
        "FP": 134,
        "TP": 117,
    },
    {
        "Name": "Tyron Rock",
        "Nickname": "Rock",
        "Description": "Doesn't mind playing dangerously since being brainwashed.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/brainwashing/Rock.png",
        "Team": "Brainwashing",
        "TeamSprite": "./images/emblems/Brainwashing.png",
        "Game": "IE1",
        "SM1": special_moves[97],
        "SM2": special_moves[96],
        "SM3": special_moves[47],
        "SM4": special_moves[102],
        "Kick": 51,
        "Body": 46,
        "Control": 46,
        "Guard": 48,
        "Speed": 48,
        "Stamina": 47,
        "Guts": 52,
        "FP": 149,
        "TP": 112,
    },
    {
        "Name": "Francis Tell",
        "Nickname": "Tell",
        "Description": "Follows instructions religiously after getting brainwashed.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/brainwashing/Tell.png",
        "Team": "Brainwashing",
        "TeamSprite": "./images/emblems/Brainwashing.png",
        "Game": "IE1",
        "SM1": special_moves[48],
        "SM2": special_moves[79],
        "SM3": special_moves[47],
        "SM4": special_moves[13],
        "Kick": 44,
        "Body": 53,
        "Control": 48,
        "Guard": 46,
        "Speed": 45,
        "Stamina": 44,
        "Guts": 47,
        "FP": 145,
        "TP": 109,
    },
    {
        "Name": "Samuel Buster",
        "Nickname": "Buster",
        "Description": "Plays aggressively close to the edge since being brainwashed.",
        "Gender": ".Buster/images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/brainwashing/Buster.png",
        "Team": "Brainwashing",
        "TeamSprite": "./images/emblems/Brainwashing.png",
        "Game": "IE1",
        "SM1": special_moves[48],
        "SM2": special_moves[93],
        "SM3": special_moves[47],
        "SM4": special_moves[102],
        "Kick": 55,
        "Body": 46,
        "Control": 52,
        "Guard": 49,
        "Speed": 48,
        "Stamina": 50,
        "Guts": 49,
        "FP": 125,
        "TP": 113,
    },
    {
        "Name": "Jonathan Seller",
        "Nickname": "Seller",
        "Description": "This solitary player is made to feel like he's under immense pressure to win.",
        "Gender": ".Buster/images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/brainwashing/Seller.png",
        "Team": "Brainwashing",
        "TeamSprite": "./images/emblems/Brainwashing.png",
        "Game": "IE1",
        "SM1": special_moves[79],
        "SM2": special_moves[48],
        "SM3": special_moves[47],
        "SM4": special_moves[38],
        "Kick": 55,
        "Body": 50,
        "Control": 50,
        "Guard": 49,
        "Speed": 55,
        "Stamina": 45,
        "Guts": 46,
        "FP": 132,
        "TP": 113,
    },
    {
        "Name": "Victor Kind",
        "Nickname": "Kind",
        "Description": "Brainwashed into believing that his team's tactics are the best.",
        "Gender": ".Buster/images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/brainwashing/Kind.png",
        "Team": "Brainwashing",
        "TeamSprite": "./images/emblems/Brainwashing.png",
        "Game": "IE1",
        "SM1": special_moves[47],
        "SM2": special_moves[79],
        "SM3": special_moves[48],
        "SM4": special_moves[34],
        "Kick": 49,
        "Body": 53,
        "Control": 48,
        "Guard": 51,
        "Speed": 48,
        "Stamina": 53,
        "Guts": 46,
        "FP": 134,
        "TP": 109,
    },
    {
        "Name": "Neil Turner",
        "Nickname": "Turner",
        "Description": "Used to be gentle, but became more aggressive after brainwashing.",
        "Gender": ".Buster/images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/brainwashing/Turner.png",
        "Team": "Brainwashing",
        "TeamSprite": "./images/emblems/Brainwashing.png",
        "Game": "IE1",
        "SM1": special_moves[96],
        "SM2": special_moves[48],
        "SM3": special_moves[38],
        "SM4": special_moves[47],
        "Kick": 48,
        "Body": 48,
        "Control": 52,
        "Guard": 52,
        "Speed": 44,
        "Stamina": 50,
        "Guts": 45,
        "FP": 121,
        "TP": 108,
    },
    {
        "Name": "Reg Underwood",
        "Nickname": "Under",
        "Description": "Accepted brainwashing to become a pro and help his poor family.",
        "Gender": ".Buster/images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/GK.png",
        "Sprite": "./images/players/ie1/brainwashing/Under.png",
        "Team": "Brainwashing",
        "TeamSprite": "./images/emblems/Brainwashing.png",
        "Game": "IE1",
        "SM1": special_moves[48],
        "SM2": special_moves[79],
        "SM3": special_moves[47],
        "SM4": special_moves[27],
        "Kick": 44,
        "Body": 40,
        "Control": 40,
        "Guard": 69,
        "Speed": 48,
        "Stamina": 42,
        "Guts": 70,
        "FP": 121,
        "TP": 115,
    },
    {
        "Name": "Patrick Stiller",
        "Nickname": "Stiller",
        "Description": "Brainwashing allowed him to reveal his true self.",
        "Gender": ".Buster/images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/brainwashing/Stiller.png",
        "Team": "Brainwashing",
        "TeamSprite": "./images/emblems/Brainwashing.png",
        "Game": "IE1",
        "SM1": special_moves[48],
        "SM2": special_moves[103],
        "SM3": special_moves[15],
        "SM4": special_moves[31],
        "Kick": 53,
        "Body": 44,
        "Control": 47,
        "Guard": 52,
        "Speed": 44,
        "Stamina": 46,
        "Guts": 53,
        "FP": 134,
        "TP": 117,
    },
    {
        "Name": "Charles Oughtry",
        "Nickname": "Oughtry",
        "Description": "Undertook brainwashing to cheer up his sick soccer-loving brother.",
        "Gender": ".Buster/images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/brainwashing/Oughtry.png",
        "Team": "Brainwashing",
        "TeamSprite": "./images/emblems/Brainwashing.png",
        "Game": "IE1",
        "SM1": special_moves[79],
        "SM2": special_moves[14],
        "SM3": special_moves[47],
        "SM4": special_moves[96],
        "Kick": 55,
        "Body": 52,
        "Control": 45,
        "Guard": 45,
        "Speed": 46,
        "Stamina": 44,
        "Guts": 48,
        "FP": 127,
        "TP": 113,
    },
    {
        "Name": "Clive Mooney",
        "Nickname": "Mooney",
        "Description": "Thanks to brainwashing, he never remembers the fouls he commits.",
        "Gender": ".Buster/images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/brainwashing/Mooney.png",
        "Team": "Brainwashing",
        "TeamSprite": "./images/emblems/Brainwashing.png",
        "Game": "IE1",
        "SM1": special_moves[96],
        "SM2": special_moves[41],
        "SM3": special_moves[97],
        "SM4": special_moves[94],
        "Kick": 53,
        "Body": 49,
        "Control": 54,
        "Guard": 50,
        "Speed": 55,
        "Stamina": 53,
        "Guts": 46,
        "FP": 138,
        "TP": 101,
    },
    {
        "Name": "Neil Waters",
        "Nickname": "Waters",
        "Description": "Brainwashing helped him look down on those who used to belittle him.",
        "Gender": ".Buster/images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/brainwashing/Waters.png",
        "Team": "Brainwashing",
        "TeamSprite": "./images/emblems/Brainwashing.png",
        "Game": "IE1",
        "SM1": special_moves[77],
        "SM2": special_moves[47],
        "SM3": special_moves[96],
        "SM4": special_moves[6],
        "Kick": 52,
        "Body": 48,
        "Control": 51,
        "Guard": 52,
        "Speed": 45,
        "Stamina": 54,
        "Guts": 45,
        "FP": 151,
        "TP": 101,
    },
    {
        "Name": "Suzanne Yuma",
        "Nickname": "Yuma",
        "Description": "A greengrocing gran who's good at keeping vegetables and footballs.",
        "Gender": "./images/genders/Female.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/GK.png",
        "Sprite": "./images/players/ie1/streetsallys/Yuma.png",
        "Team": "Street Sally's",
        "TeamSprite": "./images/emblems/Street_Sally.png",
        "Game": "IE1",
        "SM1": special_moves[90],
        "SM2": special_moves[104],
        "SM3": special_moves[55],
        "SM4": special_moves[77],
        "Kick": 44,
        "Body": 44,
        "Control": 43,
        "Guard": 56,
        "Speed": 49,
        "Stamina": 46,
        "Guts": 45,
        "FP": 129,
        "TP": 80,
    },
    {
        "Name": "Tammy Fielding",
        "Nickname": "Fielding",
        "Description": "This stationery store lady is sharp as a pencil and hard as nails.",
        "Gender": "./images/genders/Female.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/streetsallys/Fielding.png",
        "Team": "Street Sally's",
        "TeamSprite": "./images/emblems/Street_Sally.png",
        "Game": "IE1",
        "SM1": special_moves[59],
        "SM2": special_moves[12],
        "SM3": special_moves[13],
        "SM4": special_moves[66],
        "Kick": 44,
        "Body": 49,
        "Control": 48,
        "Guard": 51,
        "Speed": 48,
        "Stamina": 44,
        "Guts": 40,
        "FP": 121,
        "TP": 81,
    },
    {
        "Name": "Louis Hillside",
        "Nickname": "Knuckles",
        "Description": "Has thumbs like hammers after years as a chiropractor.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/streetsallys/Knuckles.png",
        "Team": "Street Sally's",
        "TeamSprite": "./images/emblems/Street_Sally.png",
        "Game": "IE1",
        "SM1": special_moves[77],
        "SM2": special_moves[78],
        "SM3": special_moves[98],
        "SM4": special_moves[8],
        "Kick": 60,
        "Body": 52,
        "Control": 51,
        "Guard": 41,
        "Speed": 41,
        "Stamina": 48,
        "Guts": 49,
        "FP": 136,
        "TP": 72,
    },
    {
        "Name": "Ness Sheldon",
        "Nickname": "Sheldon",
        "Description": "An experienced doctor whose only flaw is a lack of self-confidence.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/streetsallys/Sheldon.png",
        "Team": "Street Sally's",
        "TeamSprite": "./images/emblems/Street_Sally.png",
        "Game": "IE1",
        "SM1": special_moves[77],
        "SM2": special_moves[50],
        "SM3": special_moves[104],
        "SM4": special_moves[42],
        "Kick": 42,
        "Body": 48,
        "Control": 45,
        "Guard": 53,
        "Speed": 42,
        "Stamina": 40,
        "Guts": 43,
        "FP": 127,
        "TP": 84,
    },
    {
        "Name": "Lizzy Squirrel",
        "Nickname": "Squirrel",
        "Description": "This bookshop clerk hates window shoppers, browsers and ageism.",
        "Gender": "./images/genders/Female.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/streetsallys/Squirrel.png",
        "Team": "Street Sally's",
        "TeamSprite": "./images/emblems/Street_Sally.png",
        "Game": "IE1",
        "SM1": special_moves[83],
        "SM2": special_moves[62],
        "SM3": special_moves[41],
        "SM4": special_moves[23],
        "Kick": 43,
        "Body": 44,
        "Control": 50,
        "Guard": 45,
        "Speed": 47,
        "Stamina": 45,
        "Guts": 44,
        "FP": 129,
        "TP": 137,
    },
    {
        "Name": "Kippy Jones",
        "Nickname": "Jones",
        "Description": "Spends more time playing chess than at the local chamber of commerce.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/streetsallys/Jones.png",
        "Team": "Street Sally's",
        "TeamSprite": "./images/emblems/Street_Sally.png",
        "Game": "IE1",
        "SM1": special_moves[41],
        "SM2": special_moves[14],
        "SM3": special_moves[33],
        "SM4": special_moves[88],
        "Kick": 48,
        "Body": 51,
        "Control": 47,
        "Guard": 51,
        "Speed": 43,
        "Stamina": 42,
        "Guts": 51,
        "FP": 123,
        "TP": 129,
    },
    {
        "Name": "Fayette Riversong",
        "Nickname": "Riversong",
        "Description": "A talented busker with a huge following of stray dog 'fans'.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/streetsallys/Riversong.png",
        "Team": "Street Sally's",
        "TeamSprite": "./images/emblems/Street_Sally.png",
        "Game": "IE1",
        "SM1": special_moves[3],
        "SM2": special_moves[83],
        "SM3": special_moves[93],
        "SM4": special_moves[34],
        "Kick": 40,
        "Body": 50,
        "Control": 50,
        "Guard": 48,
        "Speed": 40,
        "Stamina": 42,
        "Guts": 47,
        "FP": 121,
        "TP": 61,
    },
    {
        "Name": "Samantha Moonlight",
        "Nickname": "Sally",
        "Description": "She runs the Golden Temple. Her daughter also plays football.",
        "Gender": "./images/genders/Female.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/streetsallys/Sally.png",
        "Team": "Street Sally's",
        "TeamSprite": "./images/emblems/Street_Sally.png",
        "Game": "IE1",
        "SM1": special_moves[19],
        "SM2": special_moves[91],
        "SM3": special_moves[40],
        "SM4": special_moves[89],
        "Kick": 52,
        "Body": 43,
        "Control": 42,
        "Guard": 48,
        "Speed": 41,
        "Stamina": 44,
        "Guts": 50,
        "FP": 123,
        "TP": 68,
    },
    {
        "Name": "Mitch Sandstone",
        "Nickname": "Sandstone",
        "Description": "A pub landlord who has a bit of trouble keeping track of his stock.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/streetsallys/Sandstone.png",
        "Team": "Street Sally's",
        "TeamSprite": "./images/emblems/Street_Sally.png",
        "Game": "IE1",
        "SM1": special_moves[3],
        "SM2": special_moves[36],
        "SM3": special_moves[94],
        "SM4": special_moves[97],
        "Kick": 54,
        "Body": 58,
        "Control": 41,
        "Guard": 48,
        "Speed": 45,
        "Stamina": 46,
        "Guts": 51,
        "FP": 125,
        "TP": 61,
    },
    {
        "Name": "Eddie Prentice",
        "Nickname": "Prentice",
        "Description": "A CD shop owner who loves to talk about music rather than sell CDs.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/streetsallys/Prentice.png",
        "Team": "Street Sally's",
        "TeamSprite": "./images/emblems/Street_Sally.png",
        "Game": "IE1",
        "SM1": special_moves[93],
        "SM2": special_moves[40],
        "SM3": special_moves[34],
        "SM4": special_moves[15],
        "Kick": 46,
        "Body": 46,
        "Control": 56,
        "Guard": 44,
        "Speed": 42,
        "Stamina": 48,
        "Guts": 49,
        "FP": 116,
        "TP": 73,
    },
    {
        "Name": "Alf Holmes",
        "Nickname": "Holmes",
        "Description": "At home, he adores his family, but secretly he prefers football.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/GK.png",
        "Sprite": "./images/players/ie1/streetsallys/Holmes.png",
        "Team": "Street Sally's",
        "TeamSprite": "./images/emblems/Street_Sally.png",
        "Game": "IE1",
        "SM1": special_moves[3],
        "SM2": special_moves[83],
        "SM3": special_moves[31],
        "SM4": special_moves[78],
        "Kick": 34,
        "Body": 28,
        "Control": 34,
        "Guard": 64,
        "Speed": 39,
        "Stamina": 31,
        "Guts": 77,
        "FP": 81,
        "TP": 174,
    },
    {
        "Name": "Ian Stager",
        "Nickname": "Stager",
        "Description": "He loves the theatre so much that he never misses the front row.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/streetsallys/Stager.png",
        "Team": "Street Sally's",
        "TeamSprite": "./images/emblems/Street_Sally.png",
        "Game": "IE1",
        "SM1": special_moves[58],
        "SM2": special_moves[33],
        "SM3": special_moves[94],
        "SM4": special_moves[13],
        "Kick": 40,
        "Body": 49,
        "Control": 44,
        "Guard": 51,
        "Speed": 49,
        "Stamina": 50,
        "Guts": 51,
        "FP": 129,
        "TP": 81,
    },
    {
        "Name": "Fred Crumb",
        "Nickname": "Crumb",
        "Description": "His wife got angry when he baked a football-shaped loaf at his bakery.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/streetsallys/Crumb.png",
        "Team": "Street Sally's",
        "TeamSprite": "./images/emblems/Street_Sally.png",
        "Game": "IE1",
        "SM1": special_moves[15],
        "SM2": special_moves[22],
        "SM3": special_moves[11],
        "SM4": special_moves[105],
        "Kick": 40,
        "Body": 44,
        "Control": 44,
        "Guard": 43,
        "Speed": 44,
        "Stamina": 48,
        "Guts": 45,
        "FP": 121,
        "TP": 72,
    },
    {
        "Name": "Doug Baughan",
        "Nickname": "Baughan",
        "Description": "A keen inventor who once made shoes with wings. (They flew off.)",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/streetsallys/Baughan.png",
        "Team": "Street Sally's",
        "TeamSprite": "./images/emblems/Street_Sally.png",
        "Game": "IE1",
        "SM1": special_moves[3],
        "SM2": special_moves[23],
        "SM3": special_moves[96],
        "SM4": special_moves[29],
        "Kick": 45,
        "Body": 41,
        "Control": 46,
        "Guard": 48,
        "Speed": 40,
        "Stamina": 51,
        "Guts": 44,
        "FP": 116,
        "TP": 68,
    },
    {
        "Name": "Pip Daltry",
        "Nickname": "Daltry",
        "Description": "Only on the team to make up the numbers. Oblivious to the rules.",
        "Gender": "./images/genders/Female.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/streetsallys/Daltry.png",
        "Team": "Street Sally's",
        "TeamSprite": "./images/emblems/Street_Sally.png",
        "Game": "IE1",
        "SM1": special_moves[10],
        "SM2": special_moves[18],
        "SM3": special_moves[82],
        "SM4": special_moves[33],
        "Kick": 44,
        "Body": 45,
        "Control": 49,
        "Guard": 51,
        "Speed": 49,
        "Stamina": 40,
        "Guts": 43,
        "FP": 114,
        "TP": 60,
    },
    // Inazuma Eleven 2
    {
        "Name": "Janus",
        "Nickname": "Janus",
        "Description": "A cold-hearted youth who thinks that those who lose are worthless.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie2/Janus.png",
        "Team": "Gemini Storm",
        "TeamSprite": "./images/emblems/Gemini_Storm.png",
        "Game": "IE2",
        "SM1": special_moves[67],
        "SM2": special_moves[68],
        "SM3": special_moves[69],
        "SM4": special_moves[70],
        "Kick": 63,
        "Body": 63,
        "Control": 73,
        "Guard": 61,
        "Speed": 68,
        "Stamina": 51,
        "Guts": 71,
        "FP": 173,
        "TP": 89,
    },
    // Inazuma Eleven 3
    {
        "Name": "Bash Lancer",
        "Nickname": "Bash",
        "Description": "Team Ogre's strongest soldier, he crushes his enemies with a cool smile.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie3/Bash.png",
        "Team": "Team Ogre",
        "TeamSprite": "./images/emblems/Ogre.png",
        "Game": "IE3",
        "SM1": special_moves[71],
        "SM2": special_moves[72],
        "SM3": special_moves[73],
        "SM4": special_moves[74],
        "Kick": 81,
        "Body": 51,
        "Control": 52,
        "Guard": 52,
        "Speed": 72,
        "Stamina": 72,
        "Guts": 65,
        "FP": 127,
        "TP": 152,
    },
    // Ajouter d'autres joueurs ici
  ];