var players = [
    // Inazuma Eleven 1
    {
        "Name": "Mark Evans",
        "Nickname": "Mark",
        "Description": "No one burns with a fiercer passion for football than Raimon's fearless captain!",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/GK.png",
        "Sprite": "./images/players/ie1/Mark.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": "[" + special_moves[1].element + "] " + special_moves[1].name + " (" + special_moves[1].TP + " TP)" + " [" + special_moves[1].type + "]",
        "SM2": "[" + special_moves[3].element + "] " + special_moves[3].name + " (" + special_moves[3].TP + " TP)" + " [" + special_moves[3].type + "]",
        "SM3": "[" + special_moves[4].element + "] " + special_moves[4].name + " (" + special_moves[4].TP + " TP)" + " [" + special_moves[4].type + "]",
        "SM4": "[" + special_moves[5].element + "] " + special_moves[5].name + " (" + special_moves[5].TP + " TP)" + " [" + special_moves[5].type + "]",
        "Kick": 72,
        "Body": 72,
        "Control": 70,
        "Guard": 77,
        "Speed": 68,
        "Stamina": 69,
        "Guts": 79,
        "FP": 191,
        "TP": 184,
    },
    {
        "Name": "Jack Wallside",
        "Nickname": "Jack",
        "Description": "This large-bodied defender forms a defensive wall, all by himself.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Earth.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/Jack.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": "[" + special_moves[6].element + "] " + special_moves[6].name + " (" + special_moves[6].TP + " TP)" + " [" + special_moves[6].type + "]",
        "SM2": "[" + special_moves[7].element + "] " + special_moves[7].name + " (" + special_moves[7].TP + " TP)" + " [" + special_moves[7].type + "]",
        "SM3": "[" + special_moves[8].element + "] " + special_moves[8].name + " (" + special_moves[8].TP + " TP)" + " [" + special_moves[8].type + "]",
        "SM4": "[" + special_moves[9].element + "] " + special_moves[9].name + " (" + special_moves[9].TP + " TP)" + " [" + special_moves[9].type + "]",
        "Kick": 62,
        "Body": 68,
        "Control": 62,
        "Guard": 66,
        "Speed": 49,
        "Stamina": 54,
        "Guts": 54,
        "FP": 206,
        "TP": 165,
    },
    {
        "Name": "Jim Wraith",
        "Nickname": "Jim",
        "Description": "The colour of his eyes is a mystery thanks to his fringe.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/Jim.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": "[" + special_moves[10].element + "] " + special_moves[10].name + " (" + special_moves[10].TP + " TP)" + " [" + special_moves[10].type + "]",
        "SM2": "[" + special_moves[11].element + "] " + special_moves[11].name + " (" + special_moves[11].TP + " TP)" + " [" + special_moves[11].type + "]",
        "SM3": "[" + special_moves[12].element + "] " + special_moves[12].name + " (" + special_moves[12].TP + " TP)" + " [" + special_moves[12].type + "]",
        "SM4": "[" + special_moves[13].element + "] " + special_moves[13].name + " (" + special_moves[13].TP + " TP)" + " [" + special_moves[13].type + "]",
        "Kick": 58,
        "Body": 53,
        "Control": 75,
        "Guard": 59,
        "Speed": 53,
        "Stamina": 62,
        "Guts": 60,
        "FP": 195,
        "TP": 140,
    },
    {
        "Name": "Nathan Swift",
        "Nickname": "Nathan",
        "Description": "A nimble defender. He has been friends with Endou for a long time.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/Nathan.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": "[" + special_moves[14].element + "] " + special_moves[14].name + " (" + special_moves[14].TP + " TP)" + " [" + special_moves[14].type + "]",
        "SM2": "[" + special_moves[15].element + "] " + special_moves[15].name + " (" + special_moves[15].TP + " TP)" + " [" + special_moves[15].type + "]",
        "SM3": "[" + special_moves[16].element + "] " + special_moves[16].name + " (" + special_moves[16].TP + " TP)" + " [" + special_moves[16].type + "]",
        "SM4": "[" + special_moves[17].element + "] " + special_moves[17].name + " (" + special_moves[17].TP + " TP)" + " [" + special_moves[17].type + "]",
        "Kick": 64,
        "Body": 58,
        "Control": 68,
        "Guard": 54,
        "Speed": 76,
        "Stamina": 58,
        "Guts": 56,
        "FP": 169,
        "TP": 156,
    },
    {
        "Name": "Tod Ironside",
        "Nickname": "Tod",
        "Description": "The team's mood-maker's great courage makes up for his small size.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/Tod.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": "[" + special_moves[18].element + "] " + special_moves[18].name + " (" + special_moves[18].TP + " TP)" + " [" + special_moves[18].type + "]",
        "SM2": "[" + special_moves[19].element + "] " + special_moves[19].name + " (" + special_moves[19].TP + " TP)" + " [" + special_moves[19].type + "]",
        "SM3": "[" + special_moves[20].element + "] " + special_moves[20].name + " (" + special_moves[20].TP + " TP)" + " [" + special_moves[20].type + "]",
        "SM4": "[" + special_moves[21].element + "] " + special_moves[21].name + " (" + special_moves[21].TP + " TP)" + " [" + special_moves[21].type + "]",
        "Kick": 54,
        "Body": 55,
        "Control": 53,
        "Guard": 56,
        "Speed": 59,
        "Stamina": 56,
        "Guts": 65,
        "FP": 184,
        "TP": 161,
    },
    {
        "Name": "Tim Saunders",
        "Nickname": "Timmy",
        "Description": "Although small bodied/partitioned, he is a master of kung fu footwork insert.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/Timmy.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": "[" + special_moves[22].element + "] " + special_moves[22].name + " (" + special_moves[22].TP + " TP)" + " [" + special_moves[22].type + "]",
        "SM2": "[" + special_moves[23].element + "] " + special_moves[23].name + " (" + special_moves[23].TP + " TP)" + " [" + special_moves[23].type + "]",
        "SM3": "[" + special_moves[17].element + "] " + special_moves[17].name + " (" + special_moves[17].TP + " TP)" + " [" + special_moves[17].type + "]",
        "SM4": "[" + special_moves[24].element + "] " + special_moves[24].name + " (" + special_moves[24].TP + " TP)" + " [" + special_moves[24].type + "]",
        "Kick": 63,
        "Body": 76,
        "Control": 61,
        "Guard": 60,
        "Speed": 55,
        "Stamina": 48,
        "Guts": 58,
        "FP": 156,
        "TP": 149,
    },
    {
        "Name": "Maxwell Carson",
        "Nickname": "Max",
        "Description": "Beneath his cute exterior is a a multi-skilled sportsman.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/Max.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": "[" + special_moves[15].element + "] " + special_moves[15].name + " (" + special_moves[15].TP + " TP)" + " [" + special_moves[15].type + "]",
        "SM2": "[" + special_moves[25].element + "] " + special_moves[25].name + " (" + special_moves[25].TP + " TP)" + " [" + special_moves[25].type + "]",
        "SM3": "[" + special_moves[26].element + "] " + special_moves[26].name + " (" + special_moves[26].TP + " TP)" + " [" + special_moves[26].type + "]",
        "SM4": "[" + special_moves[27].element + "] " + special_moves[27].name + " (" + special_moves[27].TP + " TP)" + " [" + special_moves[27].type + "]",
        "Kick": 60,
        "Body": 56,
        "Control": 78,
        "Guard": 64,
        "Speed": 60,
        "Stamina": 56,
        "Guts": 62,    
        "FP": 156,
        "TP": 160,
    },
    {
        "Name": "Steve Grim",
        "Nickname": "Steve",
        "Description": "A twisting aerial move that fires up a mighty shot.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wind.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/Steve.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": "[" + special_moves[28].element + "] " + special_moves[28].name + " (" + special_moves[28].TP + " TP)" + " [" + special_moves[28].type + "]",
        "SM2": "[" + special_moves[29].element + "] " + special_moves[29].name + " (" + special_moves[29].TP + " TP)" + " [" + special_moves[29].type + "]",
        "SM3": "[" + special_moves[30].element + "] " + special_moves[30].name + " (" + special_moves[30].TP + " TP)" + " [" + special_moves[30].type + "]",
        "SM4": "[" + special_moves[31].element + "] " + special_moves[31].name + " (" + special_moves[31].TP + " TP)" + " [" + special_moves[31].type + "]",
        "Kick": 62,
        "Body": 64,
        "Control": 71,
        "Guard": 64,
        "Speed": 71,
        "Stamina": 71,
        "Guts": 71, 
        "FP": 154,
        "TP": 144,
    },
    {
        "Name": "Sam Kincaid",
        "Nickname": "Sam",
        "Description": "By twisting the body, this shot",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Fire.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie1/Sam.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": "[" + special_moves[3].element + "] " + special_moves[3].name + " (" + special_moves[3].TP + " TP)" + " [" + special_moves[3].type + "]",
        "SM2": "[" + special_moves[32].element + "] " + special_moves[32].name + " (" + special_moves[32].TP + " TP)" + " [" + special_moves[32].type + "]",
        "SM3": "[" + special_moves[33].element + "] " + special_moves[33].name + " (" + special_moves[33].TP + " TP)" + " [" + special_moves[33].type + "]",
        "SM4": "[" + special_moves[34].element + "] " + special_moves[34].name + " (" + special_moves[34].TP + " TP)" + " [" + special_moves[34].type + "]",
        "Kick": 71,
        "Body": 57,
        "Control": 56,
        "Guard": 56,
        "Speed": 52,
        "Stamina": 56,
        "Guts": 76,
        "FP": 167,
        "TP": 136,
    },
    {
        "Name": "Kevin Dragonfly",
        "Nickname": "Kevin",
        "Description": "Raimon's fearsome goal scorer is really all heart.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie1/Kevin.png",
        "Team": "Raimon",
        "TeamSprite": "./images/emblems/Raimon.png",
        "Game": "IE1",
        "SM1": "[" + special_moves[36].element + "] " + special_moves[36].name + " (" + special_moves[36].TP + " TP)" + " [" + special_moves[36].type + "]",
        "SM2": "[" + special_moves[37].element + "] " + special_moves[37].name + " (" + special_moves[37].TP + " TP)" + " [" + special_moves[37].type + "]",
        "SM3": "[" + special_moves[29].element + "] " + special_moves[29].name + " (" + special_moves[29].TP + " TP)" + " [" + special_moves[29].type + "]",
        "SM4": "[" + special_moves[35].element + "] " + special_moves[35].name + " (" + special_moves[35].TP + " TP)" + " [" + special_moves[35].type + "]",
        "Kick": 71,
        "Body": 60,
        "Control": 59,
        "Guard": 61,
        "Speed": 60,
        "Stamina": 64,
        "Guts": 70,
        "FP": 195,
        "TP": 144,
    },
    {
        "Name": "Tammy Fielding",
        "Nickname": "Fielding",
        "Description": "This stationery store lady is sharp as a pencil and hard as nails.",
        "Gender": "./images/genders/Female.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/DF.png",
        "Sprite": "./images/players/ie1/Fielding.png",
        "Team": "Street Sally's",
        "TeamSprite": "./images/emblems/Street_Sally.png",
        "Game": "IE1",
        "SM1": "Black Magic	 - 17 TP",
        "SM2": "Afterimage - 25 TP",
        "SM3": "Shadow Stitch - 33 TP",
        "SM4": "Bamboo Pattern - 45 TP",
        "Kick": 44,
        "Body": 49,
        "Control": 48,
        "Guard": 51,
        "Speed": 48,
        "Stamina": 44,
        "Guts": 40,
        "FP": 121,
        "TP": 81,
    },
    // Inazuma Eleven 2
    {
        "Name": "Janus",
        "Nickname": "Janus",
        "Description": "A cold-hearted youth who thinks that those who lose are worthless.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/MF.png",
        "Sprite": "./images/players/ie2/Janus.png",
        "Team": "Gemini Storm",
        "TeamSprite": "./images/emblems/Gemini_Storm.png",
        "Game": "IE2",
        "SM1": "Astro Break - 20 TP",
        "SM2": "Warp Drive - 14 TP",
        "SM3": "Cosmic Blast - 28 TP",
        "SM4": "Gaia Break - 31 TP",
        "Kick": 63,
        "Body": 63,
        "Control": 73,
        "Guard": 61,
        "Speed": 68,
        "Stamina": 51,
        "Guts": 71,
        "FP": 173,
        "TP": 89,
    },
    // Inazuma Eleven 3
    {
        "Name": "Bash Lancer",
        "Nickname": "Bash",
        "Description": "Team Ogre's strongest soldier, he crushes his enemies with a cool smile.",
        "Gender": "./images/genders/Male.png",
        "Element": "./images/elements/Wood.png",
        "Position": "./images/positions/FW.png",
        "Sprite": "./images/players/ie3/Bash.png",
        "Team": "Team Ogre",
        "TeamSprite": "./images/emblems/Ogre.png",
        "Game": "IE3",
        "SM1": "Doom Break G2 - 67 TP",
        "SM2": "Doom Spear V3 - 46 TP",
        "SM3": "Put Your Back Into It! (Skill)",
        "SM4": "Field of Force - 57 TP",
        "Kick": 81,
        "Body": 51,
        "Control": 52,
        "Guard": 52,
        "Speed": 72,
        "Stamina": 72,
        "Guts": 65,
        "FP": 127,
        "TP": 152,
    },
    // Ajouter d'autres joueurs ici
  ];