var players = [
    // Inazuma Eleven 1
    {
        "Nickname": "Mark",
        "Description": "No one burns with a fiercer passion for football than Raimon's fearless captain!",
        "Gender": "https://inazuma-eleven.fr/team-builder/images/genders/Male.png",
        "Element": "https://inazuma-eleven.fr/team-builder/images/elements/Earth.png",
        "Position": "https://inazuma-eleven.fr/team-builder/images/positions/GK.png",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/8/8f/Bubble_sprite_mark.png",
        "Team": "Raimon",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/47/Raimon_emblem_new.png/revision/latest?cb=20171115062613",
        "Game": "IE1",
        "SM1": "[" + special_moves[1].element + "] " + special_moves[1].name + " (" + special_moves[1].TP + " TP)" + " [" + special_moves[1].type + "]",
        "SM2": "[" + special_moves[3].element + "] " + special_moves[3].name + " (" + special_moves[3].TP + " TP)" + " [" + special_moves[3].type + "]",
        "SM3": "[" + special_moves[4].element + "] " + special_moves[4].name + " (" + special_moves[4].TP + " TP)" + " [" + special_moves[4].type + "]",
        "SM4": "[" + special_moves[5].element + "] " + special_moves[5].name + " (" + special_moves[5].TP + " TP)" + " [" + special_moves[5].type + "]",
        "Kick": 72,
        "Body": 72,
        "Control": 70,
        "Guard": 77,
        "Speed": 68,
        "Stamina": 69,
        "Guts": 79,
        "FP": 191,
        "TP": 184,
    },
    {
        "Nickname": "Jack",
        "Description": "This large-bodied defender forms a defensive wall, all by himself.",
        "Gender": "https://inazuma-eleven.fr/team-builder/images/genders/Male.png",
        "Element": "https://inazuma-eleven.fr/team-builder/images/elements/Earth.png",
        "Position": "https://inazuma-eleven.fr/team-builder/images/positions/DF.png",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/9/91/%28R%29_Kabeyama.png",
        "Team": "Raimon",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/47/Raimon_emblem_new.png/revision/latest?cb=20171115062613",
        "Game": "IE1",
        "SM1": "[" + special_moves[6].element + "] " + special_moves[6].name + " (" + special_moves[6].TP + " TP)" + " [" + special_moves[6].type + "]",
        "SM2": "[" + special_moves[7].element + "] " + special_moves[7].name + " (" + special_moves[7].TP + " TP)" + " [" + special_moves[7].type + "]",
        "SM3": "[" + special_moves[8].element + "] " + special_moves[8].name + " (" + special_moves[8].TP + " TP)" + " [" + special_moves[8].type + "]",
        "SM4": "[" + special_moves[9].element + "] " + special_moves[9].name + " (" + special_moves[9].TP + " TP)" + " [" + special_moves[9].type + "]",
        "Kick": 62,
        "Body": 68,
        "Control": 62,
        "Guard": 66,
        "Speed": 49,
        "Stamina": 54,
        "Guts": 54,
        "FP": 206,
        "TP": 165,
    },
    {
        "Nickname": "Jim",
        "Description": "The colour of his eyes is a mystery thanks to his fringe.",
        "Gender": "https://inazuma-eleven.fr/team-builder/images/genders/Male.png",
        "Element": "https://inazuma-eleven.fr/team-builder/images/elements/Wood.png",
        "Position": "https://inazuma-eleven.fr/team-builder/images/positions/DF.png",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/0/08/Jin.png",
        "Team": "Raimon",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/47/Raimon_emblem_new.png/revision/latest?cb=20171115062613",
        "Game": "IE1",
        "SM1": "[" + special_moves[10].element + "] " + special_moves[10].name + " (" + special_moves[10].TP + " TP)" + " [" + special_moves[10].type + "]",
        "SM2": "[" + special_moves[11].element + "] " + special_moves[11].name + " (" + special_moves[11].TP + " TP)" + " [" + special_moves[11].type + "]",
        "SM3": "[" + special_moves[12].element + "] " + special_moves[12].name + " (" + special_moves[12].TP + " TP)" + " [" + special_moves[12].type + "]",
        "SM4": "[" + special_moves[13].element + "] " + special_moves[13].name + " (" + special_moves[13].TP + " TP)" + " [" + special_moves[13].type + "]",
        "Kick": 58,
        "Body": 53,
        "Control": 75,
        "Guard": 59,
        "Speed": 53,
        "Stamina": 62,
        "Guts": 60,
        "FP": 195,
        "TP": 140,
    },
    {
        "Nickname": "Nathan",
        "Description": "A nimble defender. He has been friends with Endou for a long time.",
        "Gender": "https://inazuma-eleven.fr/team-builder/images/genders/Male.png",
        "Element": "https://inazuma-eleven.fr/team-builder/images/elements/Wind.png",
        "Position": "https://inazuma-eleven.fr/team-builder/images/positions/DF.png",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/3/37/%28R%29_Kazemaru.png",
        "Team": "Raimon",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/47/Raimon_emblem_new.png/revision/latest?cb=20171115062613",
        "Game": "IE1",
        "SM1": "[" + special_moves[14].element + "] " + special_moves[14].name + " (" + special_moves[14].TP + " TP)" + " [" + special_moves[14].type + "]",
        "SM2": "[" + special_moves[15].element + "] " + special_moves[15].name + " (" + special_moves[15].TP + " TP)" + " [" + special_moves[15].type + "]",
        "SM3": "[" + special_moves[16].element + "] " + special_moves[16].name + " (" + special_moves[16].TP + " TP)" + " [" + special_moves[16].type + "]",
        "SM4": "[" + special_moves[17].element + "] " + special_moves[17].name + " (" + special_moves[17].TP + " TP)" + " [" + special_moves[17].type + "]",
        "Kick": 64,
        "Body": 58,
        "Control": 68,
        "Guard": 54,
        "Speed": 76,
        "Stamina": 58,
        "Guts": 56,
        "FP": 169,
        "TP": 156,
    },
    {
        "Nickname": "Tod",
        "Description": "The team's mood-maker's great courage makes up for his small size.",
        "Gender": "https://inazuma-eleven.fr/team-builder/images/genders/Male.png",
        "Element": "https://inazuma-eleven.fr/team-builder/images/elements/Fire.png",
        "Position": "https://inazuma-eleven.fr/team-builder/images/positions/DF.png",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/b/b2/Kurimatsu_Raimon.png",
        "Team": "Raimon",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/47/Raimon_emblem_new.png/revision/latest?cb=20171115062613",
        "Game": "IE1",
        "SM1": "[" + special_moves[18].element + "] " + special_moves[18].name + " (" + special_moves[18].TP + " TP)" + " [" + special_moves[18].type + "]",
        "SM2": "[" + special_moves[19].element + "] " + special_moves[19].name + " (" + special_moves[19].TP + " TP)" + " [" + special_moves[19].type + "]",
        "SM3": "[" + special_moves[20].element + "] " + special_moves[20].name + " (" + special_moves[20].TP + " TP)" + " [" + special_moves[20].type + "]",
        "SM4": "[" + special_moves[21].element + "] " + special_moves[21].name + " (" + special_moves[21].TP + " TP)" + " [" + special_moves[21].type + "]",
        "Kick": 54,
        "Body": 55,
        "Control": 53,
        "Guard": 56,
        "Speed": 59,
        "Stamina": 56,
        "Guts": 65,
        "FP": 184,
        "TP": 161,
    },
    {
        "Nickname": "Timmy",
        "Description": "Although small bodied/partitioned, he is a master of kung fu footwork insert.",
        "Gender": "https://inazuma-eleven.fr/team-builder/images/genders/Male.png",
        "Element": "https://inazuma-eleven.fr/team-builder/images/elements/Wood.png",
        "Position": "https://inazuma-eleven.fr/team-builder/images/positions/DF.png",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/43/Shourin.png",
        "Team": "Raimon",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/47/Raimon_emblem_new.png/revision/latest?cb=20171115062613",
        "Game": "IE1",
        "SM1": "[" + special_moves[22].element + "] " + special_moves[22].name + " (" + special_moves[22].TP + " TP)" + " [" + special_moves[22].type + "]",
        "SM2": "[" + special_moves[23].element + "] " + special_moves[23].name + " (" + special_moves[23].TP + " TP)" + " [" + special_moves[23].type + "]",
        "SM3": "[" + special_moves[17].element + "] " + special_moves[17].name + " (" + special_moves[17].TP + " TP)" + " [" + special_moves[17].type + "]",
        "SM4": "[" + special_moves[24].element + "] " + special_moves[24].name + " (" + special_moves[24].TP + " TP)" + " [" + special_moves[24].type + "]",
        "Kick": 63,
        "Body": 76,
        "Control": 61,
        "Guard": 60,
        "Speed": 55,
        "Stamina": 48,
        "Guts": 58,
        "FP": 156,
        "TP": 149,
    },
    {
        "Nickname": "Tammy",
        "Description": "This stationery store lady is sharp as a pencil and hard as nails.",
        "Gender": "https://inazuma-eleven.fr/team-builder/images/genders/Female.png",
        "Element": "https://inazuma-eleven.fr/team-builder/images/elements/Wood.png",
        "Position": "https://inazuma-eleven.fr/team-builder/images/positions/DF.png",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/a/aa/Fudeyama_Tome.png/revision/latest?cb=20170422093627",
        "Team": "Street Sally's",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/47/Raimon_emblem_new.png/revision/latest?cb=20171115062613",
        "Game": "IE1",
        "SM1": "Black Magic	 - 17 TP",
        "SM2": "Afterimage - 25 TP",
        "SM3": "Shadow Stitch - 33 TP",
        "SM4": "Bamboo Pattern - 45 TP",
        "Kick": 44,
        "Body": 49,
        "Control": 48,
        "Guard": 51,
        "Speed": 48,
        "Stamina": 44,
        "Guts": 40,
        "FP": 121,
        "TP": 81,
    },
    // Inazuma Eleven 2
    {
        "Nickname": "Janus",
        "Description": "A cold-hearted youth who thinks that those who lose are worthless.",
        "Gender": "https://inazuma-eleven.fr/team-builder/images/genders/Male.png",
        "Element": "https://inazuma-eleven.fr/team-builder/images/elements/Wood.png",
        "Position": "https://inazuma-eleven.fr/team-builder/images/positions/MF.png",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/5/5a/Gemini_Storm_player_10.png/revision/latest?cb=20120503175046",
        "Team": "Gemini Storm",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/47/Raimon_emblem_new.png/revision/latest?cb=20171115062613",
        "Game": "IE2",
        "SM1": "Astro Break - 20 TP",
        "SM2": "Warp Drive - 14 TP",
        "SM3": "Cosmic Blast - 28 TP",
        "SM4": "Gaia Break - 31 TP",
        "Kick": 63,
        "Body": 63,
        "Control": 73,
        "Guard": 61,
        "Speed": 68,
        "Stamina": 51,
        "Guts": 71,
        "FP": 173,
        "TP": 89,
    },
    // Inazuma Eleven 3
    {
        "Nickname": "Bash",
        "Description": "Team Ogre's strongest soldier, he crushes his enemies with a cool smile.",
        "Gender": "https://inazuma-eleven.fr/team-builder/images/genders/Male.png",
        "Element": "https://inazuma-eleven.fr/team-builder/images/elements/Wood.png",
        "Position": "https://inazuma-eleven.fr/team-builder/images/positions/FW.png",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/a/a0/Baddap_Ogre.png/revision/latest?cb=20120421025109",
        "Team": "Team Ogre",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/47/Raimon_emblem_new.png/revision/latest?cb=20171115062613",
        "Game": "IE3",
        "SM1": "Doom Break G2 - 67 TP",
        "SM2": "Doom Spear V3 - 46 TP",
        "SM3": "Put Your Back Into It! (Skill)",
        "SM4": "Field of Force - 57 TP",
        "Kick": 81,
        "Body": 51,
        "Control": 52,
        "Guard": 52,
        "Speed": 72,
        "Stamina": 72,
        "Guts": 65,
        "FP": 127,
        "TP": 152,
    },
    // Ajouter d'autres joueurs ici
  ];