var players = [
    // Inazuma Eleven 1
    {
        "Nickname": "Mark",
        "Description": "No one burns with a fiercer passion for football than Raimon's fearless captain!",
        "Gender": "https://inazuma-eleven.fr/team-builder/images/genders/Male.png",
        "Element": "https://inazuma-eleven.fr/team-builder/images/elements/Earth.png",
        "Position": "https://inazuma-eleven.fr/team-builder/images/positions/GK.png",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/8/8f/Bubble_sprite_mark.png",
        "Team": "Raimon",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/47/Raimon_emblem_new.png/revision/latest?cb=20171115062613",
        "Game": "IE1",
        "SM1": "God Hand - 21 TP",
        "SM2": "Grenade Shot - 17 TP",
        "SM3": "Majin The Hand - 46 TP",
        "SM4": "Triple Defense - 50 TP",
        "Kick": 72,
        "Body": 72,
        "Control": 70,
        "Guard": 77,
        "Speed": 68,
        "Stamina": 69,
        "Guts": 79,
        "FP": 191,
        "TP": 184,
    },
    {
        "Nickname": "Jack",
        "Description": "This large-bodied defender forms a defensive wall, all by himself.",
        "Gender": "https://inazuma-eleven.fr/team-builder/images/genders/Male.png",
        "Element": "https://inazuma-eleven.fr/team-builder/images/elements/Earth.png",
        "Position": "https://inazuma-eleven.fr/team-builder/images/positions/DF.png",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/9/91/%28R%29_Kabeyama.png",
        "Team": "Raimon",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/47/Raimon_emblem_new.png/revision/latest?cb=20171115062613",
        "Game": "IE1",
        "SM1": "The Wall - 25 TP",
        "SM2": "Super Armadillo - 22 TP",
        "SM3": "Mogura Feint - 30 TP",
        "SM4": "Mega Quake - 38 TP",
        "Kick": 62,
        "Body": 68,
        "Control": 62,
        "Guard": 66,
        "Speed": 49,
        "Stamina": 54,
        "Guts": 54,
        "FP": 206,
        "TP": 165,
    },
    {
        "Nickname": "Jim",
        "Description": "The colour of his eyes is a mystery thanks to his fringe.",
        "Gender": "https://inazuma-eleven.fr/team-builder/images/genders/Male.png",
        "Element": "https://inazuma-eleven.fr/team-builder/images/elements/Wood.png",
        "Position": "https://inazuma-eleven.fr/team-builder/images/positions/DF.png",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/0/08/Jin.png",
        "Team": "Raimon",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/47/Raimon_emblem_new.png/revision/latest?cb=20171115062613",
        "Game": "IE1",
        "SM1": "Coil Turn - 15 TP",
        "SM2": "About Face - 17 TP",
        "SM3": "Afterimage - 25 TP",
        "SM4": "Shadow Stitch - 33 TP",
        "Kick": 58,
        "Body": 53,
        "Control": 75,
        "Guard": 59,
        "Speed": 53,
        "Stamina": 62,
        "Guts": 60,
        "FP": 195,
        "TP": 140,
    },
    {
        "Nickname": "Nathan",
        "Description": "A nimble defender. He has been friends with Endou for a long time.",
        "Gender": "https://inazuma-eleven.fr/team-builder/images/genders/Male.png",
        "Element": "https://inazuma-eleven.fr/team-builder/images/elements/Wind.png",
        "Position": "https://inazuma-eleven.fr/team-builder/images/positions/DF.png",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/3/37/%28R%29_Kazemaru.png",
        "Team": "Raimon",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/47/Raimon_emblem_new.png/revision/latest?cb=20171115062613",
        "Game": "IE1",
        "SM1": "Flurry Dash	 - 15 TP",
        "SM2": "Quick Draw - 15 TP",
        "SM3": "Fire Rooster - 56 TP",
        "SM4": "Clone Faker - 36 TP",
        "Kick": 64,
        "Body": 58,
        "Control": 68,
        "Guard": 54,
        "Speed": 76,
        "Stamina": 58,
        "Guts": 56,
        "FP": 169,
        "TP": 156,
    },
    {
        "Nickname": "Tod",
        "Description": "The team's mood-maker's great courage makes up for his small size.",
        "Gender": "https://inazuma-eleven.fr/team-builder/images/genders/Male.png",
        "Element": "https://inazuma-eleven.fr/team-builder/images/elements/Fire.png",
        "Position": "https://inazuma-eleven.fr/team-builder/images/positions/DF.png",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/b/b2/Kurimatsu_Raimon.png",
        "Team": "Raimon",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/47/Raimon_emblem_new.png/revision/latest?cb=20171115062613",
        "Game": "IE1",
        "SM1": "Rodeo Clown - 15 TP",
        "SM2": "Comet Shot - 24 TP",
        "SM3": "Monkey Turn - 17 TP",
        "SM4": "Run Ball Run - 33 TP",
        "Kick": 54,
        "Body": 55,
        "Control": 53,
        "Guard": 56,
        "Speed": 59,
        "Stamina": 56,
        "Guts": 65,
        "FP": 184,
        "TP": 161,
    },
    {
        "Nickname": "Timmy",
        "Description": "Although small bodied/partitioned, he is a master of kung fu footwork insert.",
        "Gender": "https://inazuma-eleven.fr/team-builder/images/genders/Male.png",
        "Element": "https://inazuma-eleven.fr/team-builder/images/elements/Wood.png",
        "Position": "https://inazuma-eleven.fr/team-builder/images/positions/DF.png",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/43/Shourin.png",
        "Team": "Raimon",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/47/Raimon_emblem_new.png/revision/latest?cb=20171115062613",
        "Game": "IE1",
        "SM1": "Whirlwind Twister - 17 TP",
        "SM2": "Kung Fu Header - 35 TP",
        "SM3": "Clone Faker - 36 TP",
        "SM4": "Clone Shot - 51 TP",
        "Kick": 63,
        "Body": 76,
        "Control": 61,
        "Guard": 60,
        "Speed": 55,
        "Stamina": 48,
        "Guts": 58,
        "FP": 156,
        "TP": 149,
    },
    {
        "Nickname": "Tammy",
        "Description": "This stationery store lady is sharp as a pencil and hard as nails.",
        "Gender": "https://inazuma-eleven.fr/team-builder/images/genders/Female.png",
        "Element": "https://inazuma-eleven.fr/team-builder/images/elements/Wood.png",
        "Position": "https://inazuma-eleven.fr/team-builder/images/positions/DF.png",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/a/aa/Fudeyama_Tome.png/revision/latest?cb=20170422093627",
        "Team": "Street Sally's",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/47/Raimon_emblem_new.png/revision/latest?cb=20171115062613",
        "Game": "IE1",
        "SM1": "Black Magic	 - 17 TP",
        "SM2": "Afterimage - 25 TP",
        "SM3": "Shadow Stitch - 33 TP",
        "SM4": "Bamboo Pattern - 45 TP",
        "Kick": 44,
        "Body": 49,
        "Control": 48,
        "Guard": 51,
        "Speed": 48,
        "Stamina": 44,
        "Guts": 40,
        "FP": 121,
        "TP": 81,
    },
    // Inazuma Eleven 2
    {
        "Nickname": "Janus",
        "Description": "A cold-hearted youth who thinks that those who lose are worthless.",
        "Gender": "https://inazuma-eleven.fr/team-builder/images/genders/Male.png",
        "Element": "https://inazuma-eleven.fr/team-builder/images/elements/Wood.png",
        "Position": "https://inazuma-eleven.fr/team-builder/images/positions/MF.png",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/5/5a/Gemini_Storm_player_10.png/revision/latest?cb=20120503175046",
        "Team": "Gemini Storm",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/47/Raimon_emblem_new.png/revision/latest?cb=20171115062613",
        "Game": "IE2",
        "SM1": "Astro Break - 20 TP",
        "SM2": "Warp Drive - 14 TP",
        "SM3": "Cosmic Blast - 28 TP",
        "SM4": "Gaia Break - 31 TP",
        "Kick": 63,
        "Body": 63,
        "Control": 73,
        "Guard": 61,
        "Speed": 68,
        "Stamina": 51,
        "Guts": 71,
        "FP": 173,
        "TP": 89,
    },
    // Inazuma Eleven 3
    {
        "Nickname": "Bash",
        "Description": "Team Ogre's strongest soldier, he crushes his enemies with a cool smile.",
        "Gender": "https://inazuma-eleven.fr/team-builder/images/genders/Male.png",
        "Element": "https://inazuma-eleven.fr/team-builder/images/elements/Wood.png",
        "Position": "https://inazuma-eleven.fr/team-builder/images/positions/FW.png",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/a/a0/Baddap_Ogre.png/revision/latest?cb=20120421025109",
        "Team": "Team Ogre",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/47/Raimon_emblem_new.png/revision/latest?cb=20171115062613",
        "Game": "IE3",
        "SM1": "Doom Break G2 - 67 TP",
        "SM2": "Doom Spear V3 - 46 TP",
        "SM3": "Put Your Back Into It! (Skill)",
        "SM4": "Field of Force - 57 TP",
        "Kick": 81,
        "Body": 51,
        "Control": 52,
        "Guard": 52,
        "Speed": 72,
        "Stamina": 72,
        "Guts": 65,
        "FP": 127,
        "TP": 152,
    },
    // Ajouter d'autres joueurs ici
  ];